// Deck: Valletta harbour system, model concept, first results and open questions.
// Built for discussion within the Oceanography Malta Research Group, October 2026.
//
// Requires pptxgenjs, which is not part of the project environment. Install it
// in a scratch directory and run from there rather than adding node_modules to
// the repository:
//     npm install pptxgenjs && node build_concept_deck.js out.pptx
//
// The figures it embeds are generated by figure_bathymetry_overview.py,
// figure_domain_design.py, estimate_basin_modes.py, analyse_senglea_spectrum.py,
// analyse_riemann_pulse_test.py and build_mesh_v02.py. Text fit is checked on a
// rendering of the slides exported from PowerPoint.
const pptx = require("pptxgenjs");
const path = require("path");

const FIG = "C:/Users/Unipa/Documents/MaltaDT/figures";
const OUT = process.argv[2] || "valletta_model_concept.pptx";

// Palette. Deep blue dominates; orange is the single accent and matches the
// figures, so the slides and the plots read as one set.
const MID = "21295C";
const BLUE = "065A82";
const TEAL = "1C7293";
const ORANGE = "EB6834";
const WHITE = "FFFFFF";
const INK = "1A1A1A";
const MUTED = "5F6368";
const TINT = "EEF3F6";
const PALE = "CADCFC";

const HEAD = "Cambria";
const BODY = "Calibri";

const p = new pptx();
p.layout = "LAYOUT_WIDE"; // 13.33 x 7.5
p.author = "Cicero Martins Jr";
p.title = "Valletta harbour system: model concept, first results and open questions";

const W = 13.33, H = 7.5, M = 0.62;

function titleSlide(s, kicker, title, sub) {
  s.addText(kicker, { x: M, y: 0.48, w: 9, h: 0.3, fontSize: 12, bold: true,
    color: ORANGE, fontFace: BODY, charSpacing: 2, isTextBox: true, margin: 0 });
  s.addText(title, { x: M, y: 0.82, w: 12.0, h: 0.72, fontSize: 32, bold: true,
    color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
  if (sub) s.addText(sub, { x: M, y: 1.54, w: 11.9, h: 0.64, fontSize: 14,
    color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
}

function badge(s, n, x, y, col) {
  s.addShape(p.ShapeType.ellipse, { x, y, w: 0.44, h: 0.44, fill: { color: col } });
  s.addText(String(n), { x, y, w: 0.44, h: 0.44, fontSize: 15, bold: true,
    color: WHITE, align: "center", valign: "middle", fontFace: BODY, isTextBox: true, margin: 0 });
}

function note(s, txt) {
  s.addText(txt, { x: M, y: H - 0.88, w: W - 2 * M, h: 0.34, fontSize: 10.5,
    color: MUTED, italic: true, fontFace: BODY, isTextBox: true, margin: 0 });
}

// A rounded panel with a heading and a body, light or dark.
function box(s, x, y, w, h, heading, body, dark) {
  s.addShape(p.ShapeType.roundRect, { x, y, w, h,
    fill: { color: dark ? MID : TINT }, rectRadius: 0.06 });
  s.addText(heading, { x: x + 0.3, y: y + 0.18, w: w - 0.6, h: 0.3, fontSize: 13.5,
    bold: true, color: dark ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText(body, { x: x + 0.3, y: y + 0.54, w: w - 0.6, h: h - 0.66, fontSize: 11.5,
    color: dark ? PALE : INK, fontFace: BODY, lineSpacing: 15.5, valign: "top",
    isTextBox: true, margin: 0 });
}

// A table with a blue header row and alternating tint, the first column bold.
function table(s, rows, opts, align) {
  s.addTable(rows.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 0, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: opts.fontSize || 12, fontFace: BODY, valign: "middle",
    align: align ? align(j) : (j ? "right" : "left"),
  } }))), Object.assign({ border: { type: "solid", color: "E2E8EC", pt: 0.5 } }, opts));
}

// Part of a figure, given in pixels of the source, shown at a chosen width.
function crop(s, file, pxW, pxH, r, x, y, w) {
  const k = w / (r[2] - r[0]);
  s.addImage({ path: path.join(FIG, file), x, y, w: pxW * k, h: pxH * k,
    sizing: { type: "crop", x: r[0] * k, y: r[1] * k, w, h: (r[3] - r[1]) * k } });
  return (r[3] - r[1]) * k;
}

// Numbered questions in two columns, a statement in bold over its bearing.
function questions(s, qs, y0, dy, hBody) {
  qs.forEach((q, i) => {
    const col = i % 2, row = Math.floor(i / 2);
    const x = M + col * 6.08, y = y0 + row * dy;
    badge(s, q[2] || i + 1, x, y, col === 0 ? BLUE : TEAL);
    s.addText(q[0], { x: x + 0.62, y: y - 0.03, w: 5.28, h: 0.52, fontSize: 12.8,
      bold: true, color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(q[1], { x: x + 0.62, y: y + 0.5, w: 5.28, h: hBody, fontSize: 11,
      color: MUTED, fontFace: BODY, lineSpacing: 14.5, valign: "top", isTextBox: true, margin: 0 });
  });
}

/* ---------------- 1. title ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  s.addShape(p.ShapeType.ellipse, { x: 9.3, y: -1.4, w: 5.6, h: 5.6,
    fill: { color: BLUE, transparency: 55 } });
  s.addShape(p.ShapeType.ellipse, { x: 11.0, y: 3.4, w: 2.6, h: 2.6,
    fill: { color: ORANGE, transparency: 70 } });

  s.addText("WETWISE · WP3 · Maltese pilot", { x: M, y: 1.5, w: 8.4, h: 0.3,
    fontSize: 12, bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY,
    isTextBox: true, margin: 0 });
  s.addText("The Valletta harbour system", { x: M, y: 1.95, w: 8.6, h: 0.95,
    fontSize: 40, bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Model concept, first results and open questions", { x: M, y: 2.95, w: 8.6,
    h: 0.5, fontSize: 19, color: PALE, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Cicero Martins Jr", options: { bold: true, color: WHITE } },
    { text: "   Università degli Studi di Palermo", options: { color: "9FB3D1" } },
  ], { x: M, y: 4.35, w: 8.6, h: 0.3, fontSize: 13, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Visiting researcher, Oceanography Malta Research Group, University of Malta",
    { x: M, y: 4.68, w: 8.6, h: 0.3, fontSize: 12, color: "9FB3D1", fontFace: BODY,
      isTextBox: true, margin: 0 });
  s.addText("8 October 2026", { x: M, y: 5.02, w: 8.6, h: 0.3, fontSize: 12,
    color: "9FB3D1", fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("The model concept, the results obtained on the geometry, the open boundary, the Senglea record and the mesh, and the matters on which the continuation depends.");
}

/* ---------------- 2. origin ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "ORIGIN", "A framework carried across archetype",
    "The solver and the assembly are unchanged, while the governing physics differs.");

  s.addText([
    { text: "The framework originates in the Stagnone di Marsala digital twin, a coupled Delft3D FM and SWAN model of a shallow vegetated lagoon in western Sicily.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "A transfer to a second lagoon would remain within a single archetype and would test little. A transfer to a deep engineered harbour tests whether the pipeline is reusable or was fitted to one site.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "The stages that transfer constitute the reuse. Those that do not mark where the generality of the framework ends, and they are recorded as such.", options: {} },
  ], { x: M, y: 2.25, w: 5.7, h: 3.0, fontSize: 14.5, color: INK, fontFace: BODY,
       lineSpacing: 22, isTextBox: true, margin: 0 });

  const rows = [
    ["", "Stagnone", "Valletta"],
    ["Depth", "sub-metre", "12 to 20 m"],
    ["Bed", "seagrass canopy", "engineered, quay walls"],
    ["Boundary signal", "tide", "long wave, atmospheric"],
    ["Circulation driver", "wind", "the same long wave"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => ({
    text: c,
    options: {
      bold: i === 0 || j === 0,
      color: i === 0 ? WHITE : INK,
      fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
      fontSize: 12.5, fontFace: BODY, valign: "middle",
    },
  }))), { x: 6.85, y: 2.25, w: 5.86, colW: [1.86, 2.0, 2.0], rowH: 0.46,
          border: { type: "solid", color: "D6DEE3", pt: 0.5 } });

  note(s, "The transfer effort is logged stage by stage as transferred, re-parameterised or not applicable. That log constitutes the methodological result.");
  s.addNotes("The thesis contribution is framework reusability, and Valletta constitutes the harder test.");
}

/* ---------------- 3. data in hand ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "AVAILABLE DATA", "Bathymetry and coastline, co-registered",
    "CDI 4036_MEPA and the national coastline, from the holdings of the group.");

  const stats = [
    ["10 m", "merged LiDAR and sonar,\nCDI 4036_MEPA"],
    ["174 to 256×", "more resolved water cells\nthan the public EMODnet product"],
    ["99.5 %", "land and water agreement\nwith the coastline"],
  ];
  stats.forEach((st, i) => {
    const y = 2.25 + i * 1.28;
    s.addText(st[0], { x: M, y, w: 2.5, h: 0.52, fontSize: 27, bold: true,
      color: i === 1 ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: M, y: y + 0.52, w: 3.4, h: 0.6, fontSize: 12,
      color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
  });

  s.addImage({ path: path.join(FIG, "bathymetry_overview.png"),
    x: 4.55, y: 1.95, w: 5.2, h: 4.44 });
  s.addText([
    { text: "Two coordinate reference conditions\n", options: { bold: true, color: INK, breakLine: true } },
    { text: "The grids do not encode their datum. Interpreted as WGS84 they are displaced by 197 m, and no error is raised.\n", options: { color: MUTED, breakLine: true } },
    { text: "The bathymetry is ED50 and the coastline is WGS84, so neither overlays the other without a datum transformation.", options: { color: MUTED } },
  ], { x: 10.05, y: 2.6, w: 2.7, h: 2.2, fontSize: 11.5, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "Grand Harbour 1.64 km², mean depth 15.9 m. Marsamxett 1.32 km², mean depth 13.3 m.");
  s.addNotes("The 10 m grids are the contribution of the group to EMODnet. The public product gives the inlets one to three cells.");
}

/* ---------------- 4. the phenomenon ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "THE PHENOMENON", "The milgħuba as a meteotsunami",
    "An atmospherically generated long wave, known as rissaga in the Balearics and as marrobbio on the Sicilian shelf.");

  const stages = [
    ["Proudman resonance", "Energy transfers most efficiently when the atmospheric disturbance travels at the celerity of the long wave beneath it.",
     "The Malta Plateau, 99 to 190 m deep, is resonant with disturbances of 94 to 155 km h⁻¹."],
    ["Shoaling", "Green's law governs the amplification of the wave over the shoaling approach.",
     "From 150 m on the plateau into the harbours, a factor of 1.75 to 1.84."],
    ["Basin resonance", "The geometry of the basin amplifies the wave arriving at its mouth.",
     "Fundamental modes of 14.5 to 18.4 minutes in the Grand Harbour and 10.4 to 12.8 in Marsamxett."],
  ];
  stages.forEach((st, i) => {
    const x = M + i * 4.12;
    s.addShape(p.ShapeType.roundRect, { x, y: 2.72, w: 3.85, h: 2.5,
      fill: { color: TINT }, rectRadius: 0.06 });
    badge(s, i + 1, x + 0.28, 2.42, i === 0 ? ORANGE : BLUE);
    s.addText(st[0], { x: x + 0.28, y: 3.05, w: 3.3, h: 0.36, fontSize: 15.5,
      bold: true, color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: x + 0.28, y: 3.44, w: 3.3, h: 0.82, fontSize: 12,
      color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(st[2], { x: x + 0.28, y: 4.32, w: 3.3, h: 0.8, fontSize: 11,
      color: TEAL, bold: true, fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });
  });

  note(s, "At Ciutadella, Menorca, the reference site of the rissaga, the three stages compound to an order of magnitude. No equivalent decomposition has been published for Malta.");
  s.addNotes("The three-stage chain organises the study and determines the domain.");
}

/* ---------------- 5. natural periods ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "NATURAL PERIODS", "Natural periods against the observed band",
    "Quarter-wave periods, T = 4L∕√(gh), for the shelf and the inlets, and eigenmodes of the measured profile for the harbours, against the 0.2 to 2 cph band reported by Drago (2009).");

  const rows = [
    ["Element", "Basis", "Period", "Frequency", ""],
    ["Plateau to Sicily, quarter wave", "90 km, 150 m", "156 min", "0.38 cph", "within"],
    ["Plateau to Sicily, half wave", "90 km, 150 m", "78 min", "0.77 cph", "within"],
    ["Near plateau", "25 km, 120 m", "49 min", "1.24 cph", "within"],
    ["Grand Harbour", "measured profile", "14.5 to 18.4 min", "3.3 to 4.1 cph", "outside"],
    ["Marsamxett", "measured profile", "10.4 to 12.8 min", "4.7 to 5.8 cph", "outside"],
    ["A 1 km inlet", "1.0 km, 12 m", "6 min", "9.76 cph", "outside"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => {
    const head = i === 0;
    const inBand = c === "within";
    return { text: c, options: {
      bold: head || j === 0 || inBand,
      color: head ? WHITE : (inBand ? ORANGE : (c === "outside" ? MUTED : INK)),
      fill: { color: head ? BLUE : (i <= 3 ? "FDF0E9" : WHITE) },
      fontSize: 12, fontFace: BODY, valign: "middle",
      align: j === 0 ? "left" : (j === 4 ? "left" : "right"),
    } };
  })), { x: M, y: 2.5, w: 8.5, colW: [2.85, 1.5, 1.65, 1.55, 0.95], rowH: 0.375,
         border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 9.45, y: 2.5, w: 3.26, h: 3.0,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Consequence for the domain", { x: 9.75, y: 2.75, w: 2.7, h: 0.32, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The harbours respond to a shelf-scale oscillation rather than generating one.\n", options: { breakLine: true } },
    { text: "A domain confined to the harbours holds no resonator in the band, and the CMEMS boundary product carries no energy there.\n", options: { breakLine: true } },
    { text: "The domain is therefore required to contain the plateau.", options: { bold: true, color: WHITE } },
  ], { x: 9.75, y: 3.15, w: 2.7, h: 2.2, fontSize: 11.5, color: PALE,
       fontFace: BODY, lineSpacing: 15, valign: "top", isTextBox: true, margin: 0 });

  note(s, "The upper edge of the band, 2 cph, corresponds to 30 minutes, 1.6 times the upper estimate for the Grand Harbour and 2.3 times that for Marsamxett.");
  s.addNotes("The domain follows from this table. The harbour rows come from the eigenvalue calculation of the following slide and are tested against the Senglea record on the slide after it.");
}

/* ---------------- 6. basin modes ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "BASIN MODES", "Fundamental modes from the measured geometry",
    "Long-wave eigenproblem of a channel of varying section, g d∕dx(a dη∕dx) + ω² b η = 0, with η = 0 at the mouth and no flux at the head, where a(x) is the cross-section and b(x) the surface width along the geodesic distance from the mouth.");

  const h1 = crop(s, "basin_modes.png", 1650, 1350, [725, 5, 1540, 645], M, 2.42, 3.25);
  crop(s, "basin_modes.png", 1650, 1350, [0, 650, 825, 1350], M + 3.35, 2.36, 3.05);
  s.addText("Geodesic distance from the section lines, and the cross-section a(x) of the Grand Harbour with and without the St Elmo breakwater.",
    { x: M, y: 2.42 + h1 + 0.32, w: 6.4, h: 0.5, fontSize: 10.5, color: MUTED,
      fontFace: BODY, lineSpacing: 14, isTextBox: true, margin: 0 });

  table(s, [
    ["Basin", "Section line", "T₀", "T"],
    ["Grand Harbour", "outer", "16.5 min", "18.4 min"],
    ["Grand Harbour", "outer, no breakwater", "16.6 min", "18.4 min"],
    ["Grand Harbour", "inner", "14.5 min", "16.8 min"],
    ["Marsamxett", "outer", "10.7 min", "12.8 min"],
    ["Marsamxett", "inner", "10.4 min", "12.3 min"],
  ], { x: 7.3, y: 2.36, w: 5.41, colW: [1.6, 1.91, 0.95, 0.95], rowH: 0.36, fontSize: 11.5 },
  (j) => (j < 2 ? "left" : "right"));

  box(s, 7.3, 4.72, 5.41, 1.72, "Role of the St Elmo breakwater",
    "Removing the 378 m breakwater changes the period by 0.1 minute. The section at the entrance, 8,780 m², is within 6 per cent of the median section of the basin, so the inertia of the mode is distributed along the harbour and the basin is not a Helmholtz resonator.", true);

  note(s, "T₀ omits and T includes the mouth correction of Rabinovich (2009, eq. 9.16). Branches are taken in phase, so only the fundamental is reported.");
  s.addNotes("The quarter-wave resonator is the limit of this equation for a uniform channel and the Helmholtz resonator its limit for a narrow neck ahead of a wide basin, so the geometry selects between the two idealisations. The solver returns the quarter-wave period of a uniform channel to within 0.5 per cent. The supplied coastline carries the St Elmo breakwater as a detached polygon and does not carry the Ricasoli arm as a separate feature, so the opening measures some 400 m. A narrower real opening would create the neck the supplied geometry lacks. The estimate remains first-order until the modes are extracted from the mesh.");
}

/* ---------------- 7. Senglea spectrum ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OBSERVATION", "Sea level spectrum inside the Grand Harbour",
    "Senglea radar gauge, JRC TAD device 555, sampled at 5 s, on the peninsula between Dockyard Creek and French Creek. Welch spectrum over 207 gap-free segments of 2048 minutes.");

  s.addImage({ path: path.join(FIG, "senglea_spectrum.png"), x: M, y: 2.3, w: 6.3, h: 4.3 });

  table(s, [
    ["Period", "Frequency", "Peak ∕ background", "Relation to the estimate"],
    ["23.0 min", "2.61 cph", "23.8", "longer than estimated"],
    ["16.8 min", "3.57 cph", "10.1", "within 14.5 to 18.4 min"],
    ["10.0 min", "5.98 cph", "7.6", ""],
    ["6.9 min", "8.67 cph", "15.2", "near the inlet estimate"],
  ], { x: 7.2, y: 2.3, w: 5.51, colW: [0.9, 0.95, 1.56, 2.1], rowH: 0.36, fontSize: 11.5 },
  (j) => (j === 3 ? "left" : (j === 0 ? "left" : "right")));

  box(s, 7.2, 4.24, 5.51, 2.36, "Two readings of the 23-minute peak",
    [
      { text: "It is the fundamental of the Grand Harbour, which the one-dimensional calculation would then underestimate by about a quarter.", options: { bullet: true, breakLine: true, paraSpaceAfter: 5 } },
      { text: "The 16.8-minute peak is the fundamental, and the 23-minute peak belongs to the outer approach shared by the two harbours.", options: { bullet: true, breakLine: true, paraSpaceAfter: 5 } },
      { text: "The modal structure computed by the model, or a second gauge, separates the two.", options: { bold: true, color: WHITE } },
    ], true);

  note(s, "All peaks lie above the milgħuba band, which holds 12 per cent of the variance between 0.2 and 10 cph. Between 2 and 3 cph the amplitude at Senglea is 2.8 times that at Marsaxlokk.");
  s.addNotes("Panels, from the upper left. The mean spectrum with its background, the milgħuba band shaded grey and the estimated basin band shaded blue. The ratio of the spectrum to the background, in which the four peaks stand out. The largest oscillation of the admitted windows, 8 November 2021, with a range of 0.35 m at the 23-minute period. The amplitude ratio against the gauges outside the harbour. The four peaks are present on practically every day of both windows, independently of the forcing, and are therefore properties of the geometry. The ratio against Marsaxlokk compares two coastal sites and is not a transfer function from the open sea.");
}

/* ---------------- 8. events against the record ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OBSERVATION", "Reported events against the public record",
    "The public copy of the Senglea record covers 43 per cent of the span from June 2021 to December 2024, and transmission ceased on 13 December 2024.");

  table(s, [
    ["Date", "Type", "Reported effects", "Senglea, public copy"],
    ["25 Oct 2018", "seismic tsunami", "excursions of some 25 cm at Portomaso", "before installation"],
    ["18 Jun 2019", "milgħuba", "sea bed exposed and quay overtopped in St Paul's Bay", "before installation"],
    ["30 Jun 2022", "milgħuba", "flooding at Marsaskala, St Julian's and Qawra", "no data, record resumes on 1 July"],
    ["1 Jul 2023", "milgħuba", "flooding at Marsaskala and Xemxija", "displaced level, unusable"],
    ["13 Jun 2024", "meteotsunami", "flooding of the main square of Msida", "displaced level, unusable"],
  ], { x: M, y: 2.4, w: 12.09, colW: [1.5, 1.8, 4.9, 3.89], rowH: 0.38 }, () => "left");

  box(s, M, 4.92, 5.95, 1.62, "State of the record",
    "Two windows are admitted to the analysis, 24 June to 31 December 2021 and 1 December 2022 to 31 March 2023, on monthly coverage and stability of the level. From April 2023 the level is displaced by some 2 m and the gauge transmits by day only.", false);
  box(s, 6.76, 4.92, 5.95, 1.62, "Consequence for the study",
    "None of the three events since installation is resolved in the public copy, and Portomaso returns no data from the IOC facility on those dates. The archive of the group, sea level and one-minute pressure, is the record against which the response surface is tested.", true);

  s.addNotes("Sources. University of Malta Newspoint for 2018 and 2019, Newsbook for 2022, MaltaToday for 2023 and 2024, the last citing the Oceanography Malta Research Group. Upward radar echoes from vessels, rain and spray are removed by the lower envelope of the 5 s samples, and episodes of reference offset of 1.3 to 2.1 m are removed before the spectrum is computed. The choice of windows is to be confirmed within the group. The displaced level is compatible with the radar ranging to a vessel or pontoon beneath it, which is a conjecture.");
}

/* ---------------- 9. the domain ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, EXTENT", "Extent over the plateau, and its cost",
    null);
  s.addImage({ path: path.join(FIG, "domain_design.png"), x: M, y: 1.72, w: 12.09, h: 5.42 });
  s.addNotes("Domain B, roughly 86 by 66 km, east to 15 degrees, short of the escarpment. Stopping there is also what keeps sigma layers defensible.");
}

/* ---------------- 10. resolution and layers ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, DISCRETISATION", "Resolution set by the geometry of the inlets",
    "A 17-minute wave in 16 m of water is 12.8 km long, so the wavelength imposes no constraint. The planform of the inlets is the feature to be resolved.");

  s.addText("Measured channel width", { x: M, y: 2.3, w: 5.5, h: 0.32, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Half the channel length of Marsamxett is narrower than 135 m, and a third narrower than 50 m.", options: { breakLine: true, paraSpaceAfter: 8 } },
    { text: "Four to five cells carry the conveyance of a channel, eight to ten resolve the flow across it.", options: {} },
  ], { x: M, y: 2.68, w: 5.4, h: 1.1, fontSize: 12.5, color: INK, fontFace: BODY,
       lineSpacing: 17, valign: "top", isTextBox: true, margin: 0 });

  const grad = [
    ["Zone", "Cell size"],
    ["Harbour channels narrower than 150 m", "15 m"],
    ["Harbour basins and their mouths", "30 m"],
    ["Within 1 km of the coast", "120 m"],
    ["Within 5 km of the coast", "480 m"],
    ["Open plateau", "1920 m"],
  ];
  s.addTable(grad.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 1, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: 12, fontFace: BODY, valign: "middle", align: j ? "right" : "left",
  } }))), { x: M, y: 3.9, w: 5.4, colW: [3.9, 1.5], rowH: 0.375,
            border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 2.3, w: 6.16, h: 1.62,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("Mesh and time step", { x: 6.85, y: 2.5, w: 5.6, h: 0.3, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("26,766 faces. Under a resonant long wave the time step is 3.7 s, set by the 15 m cells of the channels, which samples a 17-minute wave some 280 times per cycle. The 10 m of the source data is the floor, and below 15 m a mesh interpolates rather than resolves.",
    { x: 6.85, y: 2.86, w: 5.6, h: 0.95, fontSize: 12, color: INK, fontFace: BODY,
      lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 4.08, w: 6.16, h: 2.05,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Vertical, 12 to 15 sigma layers", { x: 6.85, y: 4.28, w: 5.6, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The count is set by residence time, not by the seiche, which is barotropic. Fifteen layers give roughly one metre at the bed in the basins.\n", options: { breakLine: true } },
    { text: "Sigma is defensible only because the domain stops short of the escarpment, where the plateau gradient is one part in a thousand.", options: {} },
  ], { x: 6.85, y: 4.64, w: 5.6, h: 1.3, fontSize: 12, color: PALE,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "On the wave side, two nested SWAN grids at 1200 and 250 m. The finer agrees with the SWAN downscaling of the group at 1∕500°, arrived at independently.");
  s.addNotes("A question for Deltares concerns whether sigma holds from 15 m to 150 m, or whether a z-sigma hybrid is indicated. The wave nest was sized from the width of the harbour entrances and landed within a quarter of the resolution already in use on this coast, which is an independent check on the choice.");
}

/* ---------------- 11. mesh as built ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, MESH", "Mesh of the domain and its measured cost",
    "Quadtree refinement by zone, built in UTM 33N and transformed to WGS84, accepted by D-Flow FM 2026.01 at rest and under a forced long wave.");

  s.addImage({ path: path.join(FIG, "mesh_v02.png"), x: M, y: 2.3, w: 8.4, h: 3.36 });

  const stats = [
    ["26,766", "faces, of which some 12,000\nin the harbours"],
    ["3.7 s", "time step under a 25-minute wave\nof 0.15 m at the boundary"],
    ["611 s", "wall time per simulated day,\ntwo-dimensional, serial"],
  ];
  stats.forEach((st, i) => {
    const y = 2.3 + i * 1.14;
    s.addText(st[0], { x: 9.4, y, w: 3.3, h: 0.5, fontSize: 25, bold: true,
      color: i === 1 ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: 9.4, y: y + 0.5, w: 3.3, h: 0.5, fontSize: 11.5,
      color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: M, y: 5.82, w: 12.09, h: 0.92,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText([
    { text: "Cost of the campaign. ", options: { bold: true } },
    { text: "The parametric sweep in two dimensions amounts to some 16 h of serial computation. The three-dimensional runs of renewal and validation, 160 simulated days, amount to some 45 h on 8 MPI processes, scaled from the Stagnone configuration with an uncertainty of a factor of two.", options: {} },
  ], { x: M + 0.35, y: 5.95, w: 11.4, h: 0.68, fontSize: 12, color: INK,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("The left panel shows the face size over the domain and the right panel the two harbours, with the 15 m cells in the channels narrower than 150 m. Coastal zones of 1 km and 5 km cost 37 per cent less than zones of 2 km and 15 km, with the time step and the harbour response unchanged, since the time step is set by the 15 m cells alone. Refinement carried out directly in degrees yields transitions that FM rejects as not orthogonal, which is why the mesh is built in UTM. Open matters are one edge at 0.553 in the meshkernel orthogonality measure, 1,050 shore faces with a bed at or above zero, and the gaps of the 10 m grid at the heads of Msida and Pietà Creeks.");
}

/* ---------------- 12. open boundary ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, OPEN BOUNDARY", "Reflection of the open boundary under a synthetic pulse",
    "A Gaussian hump of water level released on a flat bed at 150 m with 1500 m cells, each case compared against a reference domain without a boundary.");

  s.addImage({ path: path.join(FIG, "riemann_pulse_test.png"), x: M, y: 2.3, w: 6.15, h: 4.3 });

  table(s, [
    ["Reflected amplitude", "Riemann", "Prescribed level"],
    ["Normal incidence, channel", "0.3 to 1.3 %", "94 to 100 %"],
    ["Incidence up to 30°, basin", "5 to 9 %", "96 to 98 %"],
    ["Corner cells", "24 to 29 %", "103 %"],
  ], { x: 7.05, y: 2.3, w: 5.66, colW: [2.66, 1.4, 1.6], rowH: 0.38 });

  box(s, 7.05, 3.96, 5.66, 1.4, "Configuration adopted",
    "A Riemann boundary on all open sides, its corners more than 40 km from the harbours, written as one polyline since FM reads only the first polyline of a boundary file.", true);
  box(s, 7.05, 5.5, 5.66, 1.1, "Cases to be tested before production",
    "A residual current across the boundary, a non-zero incoming signal from CMEMS, variable depth along the boundary, and Coriolis.", false);

  s.addNotes("Panels, from the upper left. The record in the channel, where the prescribed level returns the pulse inverted and almost undiminished while the Riemann record follows the reference. A boundary cell of the square basin at 22.5 degrees. The reflection coefficient against incidence angle, with first-order theory dashed. The volume retained in the basin, which the prescribed level holds as a trapped mode. The reflected wave is the difference between each case and the reference, so incident and reflected waves need not be separated in time. The Riemann condition assumes a plane wave at normal incidence over a fluid at rest, which is why the four production cases remain to be tested. Laksono et al. (2026) apply the same boundary over the Sicilian Channel for the same reason.");
}

/* ---------------- 13. prior work and setting ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "PRIOR WORK AND SETTING", "Existing work and the matters it leaves untreated",
    "The Grand Harbour has been modelled before, and the group operates a forecasting system over the same waters.");

  s.addText("The two studies that bear on the site", { x: M, y: 2.3, w: 5.9, h: 0.32,
    fontSize: 14, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Mazas and Farrugia, ARTELIA and Infrastructure Malta. ", options: { bold: true, breakLine: false } },
    { text: "The Grand Harbour modelled for wind-wave agitation in PHAROS, against a directional climate hindcast from 1992 to 2019. Damage in the port documented for the storms of February 2019 and February 2023.\n", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "Drago (2018), the design report of the group. ", options: { bold: true, breakLine: false } },
    { text: "A relocatable model setup is requested for ad hoc local domains, and harbour flushing at the five principal harbours appears among the process-model targets, with the Deltares suite among the families to review.", options: {} },
  ], { x: M, y: 2.7, w: 5.9, h: 2.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16.5, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.95, y: 2.3, w: 5.76, h: 3.32,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Operational system of the group", { x: 7.25, y: 2.52, w: 5.2, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "ROSARIO, Princeton Ocean Model, 1∕64° and 1∕96°, nested into CMEMS.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "SWAN downscaled to the embayments at 1∕500°, about 200 m.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "ROSARIO-SHYFEM, unstructured, three-dimensional, operational to a four-day forecast, from a few kilometres to 50 m at the coast, with Lagrangian particle tracking.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "Boundary conditions derived from CMEMS, as in the present work.", options: { bullet: true } },
  ], { x: 7.25, y: 2.9, w: 5.2, h: 2.55, fontSize: 11.5, color: PALE,
       fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: M, y: 5.82, w: 12.09, h: 0.92,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText([
    { text: "The present work is a process study conducted within the group, alongside the operational system. ", options: {} },
    { text: "It differs in the resolution inside the basins, 15 to 30 m against 50 m, in the coupling to a spectral wave model, and in the frequency band it addresses.", options: {} },
  ], { x: M + 0.35, y: 5.99, w: 11.4, h: 0.62, fontSize: 12, color: INK,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("The relocatability requirement of the design report corresponds to the framework-transfer argument of the thesis, and the porting log is the evidence for it. The study complements the operational system in a band and at a resolution the forecasting configuration is not designed for.");
}

/* ---------------- 14. the question ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "RESEARCH QUESTION", "Attribution of amplification along the generation chain",
    "Proposed formulation, submitted to the group for discussion.");

  s.addShape(p.ShapeType.roundRect, { x: M, y: 2.34, w: 12.09, h: 1.42,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("Of the amplification between the open sea and the heads of the Valletta harbours, how is it partitioned between Proudman resonance over the plateau, shoaling on the approach, and resonance of the basins themselves, and which atmospheric disturbance speeds and directions maximise that chain?",
    { x: M + 0.35, y: 2.57, w: 11.4, h: 1.0, fontSize: 15, italic: true, color: INK,
      fontFace: HEAD, lineSpacing: 21, isTextBox: true, margin: 0 });

  s.addText("Basis for the formulation", { x: M, y: 4.07, w: 5.7, h: 0.32,
    fontSize: 14, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The answer requires a model, since no arrangement of gauges separates the three stages of amplification from one another.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "The prior work treats the response of a basin to a wave already present at its boundary, so the generation side is not repeated.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "The formulation depends on the standing of that prior work, on which the judgement of the group is sought.", options: { bullet: true } },
  ], { x: M, y: 4.45, w: 5.7, h: 1.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addText("Coverage of the prior work", { x: 6.95, y: 4.07, w: 5.7, h: 0.32,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Maltese coastal seiches were modelled in 2007, in a two-dimensional depth-averaged POM, for Mellieħa and St Paul's Bay, forced by a prescribed offshore long wave.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "The Grand Harbour was modelled by ARTELIA in PHAROS, for wind-wave agitation, against a directional climate hindcast from 1992 to 2019.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "Neither treats the generation of the long wave, the circulation of the harbour, or its renewal.", options: { bullet: true } },
  ], { x: 6.95, y: 4.45, w: 5.76, h: 1.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("The formulation is a proposal. Whether work on the generation side is already planned within the group, and how the effort would then be divided, is to be discussed directly. The applied companion is a map of exposure by inlet and quay, and the renewal question has independent standing under the Water Framework Directive.");
}

/* ---------------- 15. sensitivity of the mouth ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "COUNTERFACTUAL QUESTION", "Sensitivity of the basin mode to the geometry of the mouth",
    "An academic sensitivity on the class of basin, submitted to the group for judgement. No particular design is represented.");

  table(s, [
    ["Open fraction of the section", "100 m reach", "250 m reach", "500 m reach", "Helmholtz scaling"],
    ["0.75", "+1.5 %", "+2.7 %", "+4.0 %", "+15 %"],
    ["0.50", "+4.4 %", "+8.0 %", "+11.7 %", "+41 %"],
    ["0.25", "+13.1 %", "+23.3 %", "+33.1 %", "+100 %"],
    ["0.10", "+37.2 %", "+62.5 %", "+84.6 %", "+216 %"],
  ], { x: M, y: 2.5, w: 7.1, colW: [2.3, 1.15, 1.15, 1.15, 1.35], rowH: 0.4, fontSize: 11.5 });

  s.addText("Lengthening of the fundamental period of the Grand Harbour, 16.5 minutes, for a restriction imposed on the measured profile over a reach centred on its narrowest section. The Helmholtz scaling, T ∝ a^(−1∕2), attributes the whole inertia of the mode to the mouth and overstates the shift by a factor of three to ten.",
    { x: M, y: 4.66, w: 7.1, h: 1.1, fontSize: 11.5, color: MUTED, fontFace: BODY,
      lineSpacing: 15.5, isTextBox: true, margin: 0 });

  box(s, 8.05, 2.5, 4.66, 1.72, "The magnitude in context",
    "A metre of sea level rise shortens these modes by 3.1 per cent. A restriction of a quarter lengthens them by 1.5 to 4 per cent. The two perturbations are of the same order.", false);
  box(s, 8.05, 4.38, 4.66, 1.92, "Exchange as the principal quantity",
    "Reaching the observed band from 18.4 minutes requires an open fraction near 0.1 over several hundred metres. The volume exchanged per cycle scales with the open section directly, so renewal responds more strongly than the mode.", true);

  note(s, "The cost is a second evaluation of the same sweep, with no new forcing, no new validation and no new configuration.");
  s.addNotes("The framing is a response curve over the class of basin. The exact geometry of any proposed structure is neither needed nor used, and the exercise carries no assessment of the project now in consultation. Whether to pursue it is among the open questions.");
}

/* ---------------- 16. the design ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "EXPERIMENTAL DESIGN", "A parametric sweep in place of a hindcast",
    "ERA5 does not resolve the atmospheric gravity waves that trigger the phenomenon, so a hindcast of individual events is not attempted.");

  const steps = [
    ["Sweep", "A moving pressure disturbance is imposed, and its speed, direction, width and duration are varied."],
    ["Response surface", "The output is a transfer function of the geometry, independent of any particular storm."],
    ["Test against the observations", "The observations serve as the test rather than as the forcing, addressing whether recorded events occur under the conditions identified as resonant."],
  ];
  steps.forEach((st, i) => {
    const y = 2.55 + i * 1.28;
    badge(s, i + 1, M, y, i === 2 ? ORANGE : BLUE);
    s.addText(st[0], { x: M + 0.68, y: y - 0.02, w: 5.0, h: 0.32, fontSize: 14.5,
      bold: true, color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: M + 0.68, y: y + 0.32, w: 6.6, h: 0.72, fontSize: 12.5,
      color: MUTED, fontFace: BODY, lineSpacing: 17, isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: 8.4, y: 2.5, w: 4.31, h: 3.4,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Bearing beyond the present study", { x: 8.7, y: 2.72, w: 3.75, h: 0.6,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "A response surface is a property of the geometry, whereas climate change acts on the distribution of the forcing.\n", options: { breakLine: true } },
    { text: "The two separate, so the surface is computed once and any later study with synoptic projections may convolve them without repeating the hydrodynamics.\n", options: { breakLine: true } },
    { text: "No climate scenario need be run through the model.", options: { bold: true, color: WHITE } },
  ], { x: 8.7, y: 3.35, w: 3.75, h: 2.3, fontSize: 11.5, color: PALE,
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  note(s, "The milgħuba floods Msida, at the head of Msida Creek inside Marsamxett, together with Marsaskala, Xemxija, Marsaxlokk and Sliema.");
  s.addNotes("Six speeds by eight directions by two widths, twelve hours each, barotropic and uncoupled, with a second evaluation over a modified mouth, amount to 96 simulated days and some 16 hours of serial computation. The dated events of 2019, 2022, 2023 and 2024 are the cases for the test, which is why the one-minute pressure records on those dates head the requests of the following slide.");
}

/* ---------------- 17. requests on the observations ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OPEN QUESTIONS, OBSERVATIONS", "Requests on the observational record",
    "The test of the response surface rests on the dated events, none of which is resolved in the public records.");

  questions(s, [
    ["Sea level from the archive of the group on the dates of the reported events",
     "Senglea and Delimara at 5 s or one minute, for 29 June to 2 July 2022, 30 June to 2 July 2023 and 12 to 14 June 2024. The public copy on the JRC server resolves none of the three."],
    ["One-minute atmospheric pressure from the PORTO stations on the same dates",
     "Elmo, Kordin and Msida first. The pressure signature is the disturbance that forces the milgħuba, and its speed and direction are the quantities located on the response surface."],
    ["History of the Senglea installation",
     "The two windows admitted to the analysis, the cause of the gaps of 2022 and of the displacement of some 2 m from April 2023, whether the gauge was relocated, and whether the IDSL units on the JRC server are the instruments of the group."],
    ["The Portomaso record at one minute or finer",
     "A gauge outside both basins on the same coast separates the two readings of the 23-minute peak, and extends the event record to the years before the Senglea installation."],
  ], 2.6, 1.9, 1.2);

  s.addNotes("These four determine whether the response surface can be tested against events at all. Sources for the events of 2022 and 2023 are press reports only, and a statement or record of the group would replace them.");
}

/* ---------------- 18. questions on scope and configuration ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OPEN QUESTIONS, SCOPE AND CONFIGURATION", "Questions on scope and configuration", null);

  questions(s, [
    ["Appropriateness of the sensitivity exercise on the harbour mouth, and the present geometry of the entrance",
     "The exercise is a response curve over the class of basin and carries no assessment of the project in consultation. Whether the 120 m Ricasoli arm narrows the present opening bears on the computed mode.", 5],
    ["Extent of prior work on the generation of the wave",
     "The 2007 study imposes the long wave at the offshore boundary. Unpublished material, dissertations and consultancy reports may have treated its generation over the shelf, which the published record does not show.", 6],
    ["Elements of ROSARIO-SHYFEM to be reflected in the configuration",
     "The treatment of the open boundary and the bathymetry inside the harbours, in particular at the heads of Msida and Pietà Creeks, where the 10 m grid has gaps.", 7],
    ["Currents, stratification and waves inside and near the harbours",
     "No instrument reports the current field or the stratification of the inner inlets. Wave validation rests on the BLUE buoy, 3.7 km offshore, the radar wave product being derived rather than measured.", 8],
    ["Levelling datum of the bathymetry against the zeros of the tide gauges",
     "The files declare ellipsoidal heights while the data are orthometric. The offset against the gauges used for validation remains to be established.", 9],
    ["Storm Harry, January 2026, as the validation case",
     "The account of the event from the monitoring network of the group would supply the storm case for the validation of the coupled wave and current configuration.", 10],
  ], 2.05, 1.62, 0.98);

  s.addNotes("Numbering continues from the preceding slide. Damage inside the port is documented for the wind-wave storms of February 2019 and February 2023. Disruption attributable to long waves specifically, held by Transport Malta and the terminals, remains open and may be raised under the second item.");
}

/* ---------------- 19. sequence ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  s.addShape(p.ShapeType.ellipse, { x: -1.9, y: 4.2, w: 5.2, h: 5.2,
    fill: { color: BLUE, transparency: 60 } });

  s.addText("SEQUENCE", { x: M, y: 0.7, w: 9, h: 0.3, fontSize: 12,
    bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Sequence to the first production runs", { x: M, y: 1.05, w: 11, h: 0.7, fontSize: 30,
    bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });

  const tl = [
    ["Completed", "Basin modes, pulse test of the boundary, Senglea spectrum, mesh of the domain."],
    ["October", "Bathymetry at the heads of Msida and Pietà Creeks, remaining boundary tests, response of the mesh to a broadband impulse."],
    ["19 October", "Delft3D User Days abstract."],
    ["2 to 4 November", "Delft3D User Days at Deltares, with the configuration questions."],
    ["November", "Parametric sweep in two dimensions, first three-dimensional runs."],
  ];
  // The timeline occupies the left column only, so the panel on the right has
  // its own band.
  tl.forEach((t, i) => {
    const y = 2.15 + i * 0.92;
    s.addShape(p.ShapeType.ellipse, { x: M + 0.05, y: y + 0.1, w: 0.17, h: 0.17,
      fill: { color: i === 2 ? ORANGE : PALE } });
    s.addText(t[0], { x: M + 0.45, y, w: 2.2, h: 0.33, fontSize: 13, bold: true,
      color: i === 2 ? ORANGE : WHITE, fontFace: BODY, valign: "top", isTextBox: true, margin: 0 });
    s.addText(t[1], { x: M + 2.7, y, w: 4.0, h: 0.8, fontSize: 12,
      color: "9FB3D1", fontFace: BODY, lineSpacing: 15, valign: "top", isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: 7.5, y: 2.15, w: 5.21, h: 3.4,
    fill: { color: BLUE, transparency: 30 }, rectRadius: 0.06 });
  s.addText("Beyond the period", { x: 7.8, y: 2.38, w: 4.6, h: 0.3, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The Stagnone twin runs containerised on the EDITO Datalab and publishes to its object storage.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "A Valletta configuration would take the same route, so the deliverable is a running pilot rather than a set of figures.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "This corresponds to the relocatable setup requested in the design report of the group.", options: { bold: true, color: WHITE } },
  ], { x: 7.8, y: 2.78, w: 4.6, h: 2.5, fontSize: 11.5, color: "DCE7F5",
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addText("Documents, figures and the reproducible analysis are in the project repository.",
    { x: M, y: 6.78, w: 6.4, h: 0.3, fontSize: 11, italic: true, color: "7F93B3",
      fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("The broadband impulse yields the modal structure of the harbours on the mesh, which decides between the two readings of the 23-minute peak. The remaining boundary tests are the residual current and the non-zero incoming signal from CMEMS. The block of 27 October to 21 November loses four working days to Delft and holds fifteen rather than nineteen. The EDITO deployment is conditional on the configuration proving stable in time, and it belongs to the last block of the period alongside the integration into the ocean.mt portal.");
}

p.writeFile({ fileName: OUT }).then(() => console.log("written", OUT));
