// Deck: Valletta harbour system, model concept, first results and open questions.
// Built for discussion within the Oceanography Malta Research Group, October 2026.
//
// Requires pptxgenjs, which is not part of the project environment. Install it
// in a scratch directory and run from there rather than adding node_modules to
// the repository:
//     npm install pptxgenjs && node build_concept_deck.js out.pptx
//
// The figures it embeds are generated by figure_bathymetry_overview.py,
// figure_domain_design.py, estimate_basin_modes.py, analyse_senglea_spectrum.py,
// analyse_riemann_pulse_test.py and build_mesh_v02.py. Text fit is checked on a
// rendering of the slides exported from PowerPoint.
//
// The first slide is a placeholder. The cover, docs/deck_cover.pptx, carries a
// photograph recoloured in PowerPoint, which pptxgenjs does not reproduce.
// copy_deck_cover.ps1 places it over the placeholder and repeats the photograph
// behind the last slide:
//     powershell -File copy_deck_cover.ps1 <docs/deck_cover.pptx> <out.pptx>
const pptx = require("pptxgenjs");
const path = require("path");

const FIG = "C:/Users/Unipa/Documents/MaltaDT/figures";
const OUT = process.argv[2] || "valletta_model_concept.pptx";

// Palette. Deep blue dominates; orange is the single accent and matches the
// figures, so the slides and the plots read as one set.
const MID = "21295C";
const BLUE = "065A82";
const TEAL = "1C7293";
const ORANGE = "EB6834";
const WHITE = "FFFFFF";
const INK = "1A1A1A";
const MUTED = "5F6368";
const TINT = "EEF3F6";
const PALE = "CADCFC";

const HEAD = "Cambria";
const BODY = "Calibri";

const p = new pptx();
p.layout = "LAYOUT_WIDE"; // 13.33 x 7.5
p.author = "Cicero Martins Jr";
p.title = "Valletta harbour system: model concept, first results and open questions";

const W = 13.33, H = 7.5, M = 0.62;

function titleSlide(s, kicker, title, sub) {
  s.addText(kicker, { x: M, y: 0.48, w: 9, h: 0.3, fontSize: 12, bold: true,
    color: ORANGE, fontFace: BODY, charSpacing: 2, isTextBox: true, margin: 0 });
  s.addText(title, { x: M, y: 0.82, w: 12.0, h: 0.72, fontSize: 32, bold: true,
    color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
  if (sub) s.addText(sub, { x: M, y: 1.54, w: 11.9, h: 0.64, fontSize: 14,
    color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
}

function badge(s, n, x, y, col) {
  s.addShape(p.ShapeType.ellipse, { x, y, w: 0.44, h: 0.44, fill: { color: col } });
  s.addText(String(n), { x, y, w: 0.44, h: 0.44, fontSize: 15, bold: true,
    color: WHITE, align: "center", valign: "middle", fontFace: BODY, isTextBox: true, margin: 0 });
}

function note(s, txt) {
  s.addText(txt, { x: M, y: H - 0.88, w: W - 2 * M, h: 0.34, fontSize: 10.5,
    color: MUTED, italic: true, fontFace: BODY, isTextBox: true, margin: 0 });
}

// A rounded panel with a heading and a body, light or dark.
function box(s, x, y, w, h, heading, body, dark) {
  s.addShape(p.ShapeType.roundRect, { x, y, w, h,
    fill: { color: dark ? MID : TINT }, rectRadius: 0.06 });
  s.addText(heading, { x: x + 0.3, y: y + 0.18, w: w - 0.6, h: 0.3, fontSize: 13.5,
    bold: true, color: dark ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText(body, { x: x + 0.3, y: y + 0.54, w: w - 0.6, h: h - 0.66, fontSize: 11.5,
    color: dark ? PALE : INK, fontFace: BODY, lineSpacing: 15.5, valign: "top",
    isTextBox: true, margin: 0 });
}

// A table with a blue header row and alternating tint, the first column bold.
function table(s, rows, opts, align) {
  s.addTable(rows.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 0, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: opts.fontSize || 12, fontFace: BODY, valign: "middle",
    align: align ? align(j) : (j ? "right" : "left"),
  } }))), Object.assign({ border: { type: "solid", color: "E2E8EC", pt: 0.5 } }, opts));
}

// Part of a figure, given in pixels of the source, shown at a chosen width.
function crop(s, file, pxW, pxH, r, x, y, w) {
  const k = w / (r[2] - r[0]);
  s.addImage({ path: path.join(FIG, file), x, y, w: pxW * k, h: pxH * k,
    sizing: { type: "crop", x: r[0] * k, y: r[1] * k, w, h: (r[3] - r[1]) * k } });
  return (r[3] - r[1]) * k;
}

// Numbered questions in two columns, a statement in bold over its bearing.
function questions(s, qs, y0, dy, hBody) {
  qs.forEach((q, i) => {
    const col = i % 2, row = Math.floor(i / 2);
    const x = M + col * 6.08, y = y0 + row * dy;
    badge(s, q[2] || i + 1, x, y, col === 0 ? BLUE : TEAL);
    s.addText(q[0], { x: x + 0.62, y: y - 0.03, w: 5.28, h: 0.52, fontSize: 12.8,
      bold: true, color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(q[1], { x: x + 0.62, y: y + 0.5, w: 5.28, h: hBody, fontSize: 11,
      color: MUTED, fontFace: BODY, lineSpacing: 14.5, valign: "top", isTextBox: true, margin: 0 });
  });
}

/* ---------------- 1. title ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  s.addShape(p.ShapeType.ellipse, { x: 9.3, y: -1.4, w: 5.6, h: 5.6,
    fill: { color: BLUE, transparency: 55 } });
  s.addShape(p.ShapeType.ellipse, { x: 11.0, y: 3.4, w: 2.6, h: 2.6,
    fill: { color: ORANGE, transparency: 70 } });

  s.addText("WETWISE · WP3 · Maltese pilot", { x: M, y: 1.5, w: 8.4, h: 0.3,
    fontSize: 12, bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY,
    isTextBox: true, margin: 0 });
  s.addText("The Valletta harbour system", { x: M, y: 1.95, w: 8.6, h: 0.95,
    fontSize: 40, bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Model concept, first results and open questions", { x: M, y: 2.95, w: 8.6,
    h: 0.5, fontSize: 19, color: PALE, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Cicero Martins Jr", options: { bold: true, color: WHITE } },
    { text: "   Università degli Studi di Palermo", options: { color: "9FB3D1" } },
  ], { x: M, y: 4.35, w: 8.6, h: 0.3, fontSize: 13, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Visiting researcher, Oceanography Malta Research Group, University of Malta",
    { x: M, y: 4.68, w: 8.6, h: 0.3, fontSize: 12, color: "9FB3D1", fontFace: BODY,
      isTextBox: true, margin: 0 });
  s.addText("8 October 2026", { x: M, y: 5.02, w: 8.6, h: 0.3, fontSize: 12,
    color: "9FB3D1", fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("The model concept, the results obtained on the geometry, the open boundary, the Senglea record and the mesh, and the matters on which the continuation depends.");
}

/* ---------------- 2. origin ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "ORIGIN", "A framework carried across archetype",
    "The solver and the assembly are unchanged, while the governing physics differs.");

  s.addText([
    { text: "The framework originates in the Stagnone di Marsala digital twin, a coupled Delft3D FM and SWAN model of a shallow vegetated lagoon in western Sicily.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "A transfer to a second lagoon would remain within a single archetype and would test little. A transfer to a deep engineered harbour tests whether the pipeline is reusable or was fitted to one site.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "The stages that transfer constitute the reuse. Those that do not mark where the generality of the framework ends, and they are recorded as such.", options: {} },
  ], { x: M, y: 2.25, w: 5.7, h: 3.0, fontSize: 14.5, color: INK, fontFace: BODY,
       lineSpacing: 22, isTextBox: true, margin: 0 });

  const rows = [
    ["", "Stagnone", "Valletta"],
    ["Depth", "sub-metre", "12 to 20 m"],
    ["Bed", "seagrass canopy", "engineered, quay walls"],
    ["Boundary signal", "tide", "long wave, atmospheric"],
    ["Circulation driver", "wind", "the same long wave"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => ({
    text: c,
    options: {
      bold: i === 0 || j === 0,
      color: i === 0 ? WHITE : INK,
      fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
      fontSize: 12.5, fontFace: BODY, valign: "middle",
    },
  }))), { x: 6.85, y: 2.25, w: 5.86, colW: [1.86, 2.0, 2.0], rowH: 0.46,
          border: { type: "solid", color: "D6DEE3", pt: 0.5 } });

  note(s, "The transfer effort is logged stage by stage as transferred, re-parameterised or not applicable. That log constitutes the methodological result.");
  s.addNotes("The thesis contribution is framework reusability, and Valletta constitutes the harder test.");
}

/* ---------------- 3. data in hand ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "AVAILABLE DATA", "Bathymetry and coastline, co-registered",
    "CDI 4036_MEPA and the national coastline, from the holdings of the group.");

  const stats = [
    ["10 m", "merged LiDAR and sonar,\nCDI 4036_MEPA"],
    ["174 to 256×", "more resolved water cells\nthan the public EMODnet product"],
    ["99.5 %", "land and water agreement\nwith the coastline"],
  ];
  stats.forEach((st, i) => {
    const y = 2.25 + i * 1.28;
    s.addText(st[0], { x: M, y, w: 2.5, h: 0.52, fontSize: 27, bold: true,
      color: i === 1 ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: M, y: y + 0.52, w: 3.4, h: 0.6, fontSize: 12,
      color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
  });

  s.addImage({ path: path.join(FIG, "bathymetry_overview.png"),
    x: 4.55, y: 1.95, w: 5.2, h: 4.44 });
  s.addText([
    { text: "Two coordinate reference conditions\n", options: { bold: true, color: INK, breakLine: true } },
    { text: "The grids do not encode their datum. Interpreted as WGS84 they are displaced by 197 m, and no error is raised.\n", options: { color: MUTED, breakLine: true } },
    { text: "The bathymetry is ED50 and the coastline is WGS84, so neither overlays the other without a datum transformation.", options: { color: MUTED } },
  ], { x: 10.05, y: 2.6, w: 2.7, h: 2.2, fontSize: 11.5, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "Grand Harbour 1.64 km², mean depth 15.9 m. Marsamxett 1.32 km², mean depth 13.3 m.");
  s.addNotes("The 10 m grids are the contribution of the group to EMODnet. The public product gives the inlets one to three cells.");
}

/* ---------------- 4. the phenomenon ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "THE PHENOMENON", "The milgħuba as a meteotsunami",
    "An atmospherically generated long wave, known as rissaga in the Balearics and as marrobbio on the Sicilian shelf.");

  const stages = [
    ["Proudman resonance", "Energy transfers most efficiently when the atmospheric disturbance travels at the celerity of the long wave beneath it.",
     "The Malta Plateau, 99 to 190 m deep, would be resonant with disturbances travelling at 94 to 155 km h⁻¹."],
    ["Shoaling", "Green's law governs the amplification of the wave over the shoaling approach.",
     "From 150 m on the plateau into the harbours, a factor of 1.75 to 1.84."],
    ["Basin resonance", "The geometry of the basin amplifies the wave arriving at its mouth.",
     "First-order estimates place the fundamental modes at 14.5 to 18.4 minutes in the Grand Harbour and 10.4 to 12.8 in Marsamxett."],
  ];
  stages.forEach((st, i) => {
    const x = M + i * 4.12;
    s.addShape(p.ShapeType.roundRect, { x, y: 2.72, w: 3.85, h: 2.5,
      fill: { color: TINT }, rectRadius: 0.06 });
    badge(s, i + 1, x + 0.28, 2.42, i === 0 ? ORANGE : BLUE);
    s.addText(st[0], { x: x + 0.28, y: 3.05, w: 3.3, h: 0.36, fontSize: 15.5,
      bold: true, color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: x + 0.28, y: 3.44, w: 3.3, h: 0.82, fontSize: 12,
      color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(st[2], { x: x + 0.28, y: 4.32, w: 3.3, h: 0.8, fontSize: 11,
      color: TEAL, bold: true, fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });
  });

  note(s, "At Ciutadella, Menorca, the reference site of the rissaga, the three stages compound to an order of magnitude. No equivalent decomposition has been published for Malta.");
  s.addNotes("The three-stage chain organises the study and determines the domain.");
}

/* ---------------- 5. natural periods ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "NATURAL PERIODS", "First-order estimates of the natural periods",
    "Quarter-wave periods, T = 4L∕√(gh), for the shelf and the inlets, and eigenmodes of the measured profile for the harbours, against the 0.2 to 2 cph band reported by Drago (2009).");

  const rows = [
    ["Element", "Basis", "Period", "Frequency", ""],
    ["Plateau to Sicily, quarter wave", "90 km, 150 m", "156 min", "0.38 cph", "within"],
    ["Plateau to Sicily, half wave", "90 km, 150 m", "78 min", "0.77 cph", "within"],
    ["Near plateau", "25 km, 120 m", "49 min", "1.24 cph", "within"],
    ["Grand Harbour", "measured profile", "14.5 to 18.4 min", "3.3 to 4.1 cph", "outside"],
    ["Marsamxett", "measured profile", "10.4 to 12.8 min", "4.7 to 5.8 cph", "outside"],
    ["A 1 km inlet", "1.0 km, 12 m", "6 min", "9.76 cph", "outside"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => {
    const head = i === 0;
    const inBand = c === "within";
    return { text: c, options: {
      bold: head || j === 0 || inBand,
      color: head ? WHITE : (inBand ? ORANGE : (c === "outside" ? MUTED : INK)),
      fill: { color: head ? BLUE : (i <= 3 ? "FDF0E9" : WHITE) },
      fontSize: 12, fontFace: BODY, valign: "middle",
      align: j === 0 ? "left" : (j === 4 ? "left" : "right"),
    } };
  })), { x: M, y: 2.5, w: 8.5, colW: [2.85, 1.5, 1.65, 1.55, 0.95], rowH: 0.375,
         border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 9.45, y: 2.5, w: 3.26, h: 3.55,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Reading for the domain", { x: 9.75, y: 2.75, w: 2.7, h: 0.32, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "On these estimates the plateau has natural periods within the band and the harbours above it, which suggests that the harbours respond to a shelf-scale oscillation.\n", options: { breakLine: true } },
    { text: "A domain confined to the harbours would then hold no resonator in the band.\n", options: { breakLine: true } },
    { text: "A domain extending over the plateau is therefore proposed.", options: { bold: true, color: WHITE } },
  ], { x: 9.75, y: 3.15, w: 2.7, h: 2.8, fontSize: 11.5, color: PALE,
       fontFace: BODY, lineSpacing: 15, valign: "top", isTextBox: true, margin: 0 });

  note(s, "The upper edge of the band, 2 cph, corresponds to 30 minutes, 1.6 times the upper estimate for the Grand Harbour and 2.3 times that for Marsamxett.");
  s.addNotes("The proposed domain follows from this table. The CMEMS boundary product is not expected to carry energy in the band. The harbour rows come from a one-dimensional eigenvalue calculation on the measured profile and are tested against the Senglea record on the following slide.");
}

/* ---------------- 6. estimated and observed modes ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "BASIN MODES", "Estimated and observed modes of the Grand Harbour",
    "A test of the harbour estimate of the preceding slide, on which the choice of domain rests, against the spectrum of the Senglea radar gauge inside the basin (JRC TAD device 555, 5 s sampling, nine months admitted).");

  s.addImage({ path: path.join(FIG, "senglea_spectrum.png"), x: M, y: 2.3, w: 6.3, h: 4.3 });

  table(s, [
    ["Observed period", "Frequency", "Peak ∕ background", "Relation to the estimate"],
    ["23.0 min", "2.61 cph", "23.8", "longer than estimated"],
    ["16.8 min", "3.57 cph", "10.1", "within 14.5 to 18.4 min"],
    ["10.0 min", "5.98 cph", "7.6", ""],
    ["6.9 min", "8.67 cph", "15.2", "near the inlet estimate"],
  ], { x: 7.2, y: 2.3, w: 5.51, colW: [1.3, 0.95, 1.26, 2.0], rowH: 0.34, fontSize: 11 },
  (j) => (j === 0 || j === 3 ? "left" : "right"));

  box(s, 7.2, 4.14, 5.51, 2.46, "Preliminary reading", [
    { text: "The observed peaks lie above the milgħuba band, in agreement with the estimate.", options: { bullet: true, breakLine: true, paraSpaceAfter: 5 } },
    { text: "The dominant peak, at 23 minutes, is longer than estimated. It may be the fundamental, underestimated by the calculation, or a mode of the approach shared by the two harbours.", options: { bullet: true, breakLine: true, paraSpaceAfter: 5 } },
    { text: "On the supplied coastline, removing the St Elmo breakwater changes the estimate by 0.1 minute.", options: { bullet: true } },
  ], true);

  note(s, "A single gauge does not separate the two readings of the 23-minute peak. The modal structure computed on the mesh, or a second gauge, would.");
  s.addNotes("The estimate comes from the long-wave eigenproblem of a channel of varying section, g d/dx(a dη/dx) + ω² b η = 0, solved on the cross-section a(x) and the surface width b(x) measured along the geodesic distance from the mouth, with the mouth correction of Rabinovich (2009, eq. 9.16). It is one-dimensional and first-order. Panels, from the upper left. The mean spectrum with its background, the milgħuba band shaded grey and the estimated basin band shaded blue. The ratio of the spectrum to the background. The largest oscillation of the admitted windows, 8 November 2021, with a range of 0.35 m. The amplitude ratio against the gauges outside the harbour. The peaks recur on practically every day of both windows, which points to the geometry rather than to the forcing. The section at the entrance is within 6 per cent of the median section of the basin, which suggests that the inertia of the mode is distributed along the harbour. Whether the Ricasoli arm narrows the real opening is unresolved, and a narrower opening would alter that reading.");
}

/* ---------------- 7. events against the record ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OBSERVATION", "Reported events against the public record",
    "The public copy of the Senglea record covers 43 per cent of the span from June 2021 to December 2024, and transmission ceased on 13 December 2024.");

  table(s, [
    ["Date", "Type", "Reported effects", "Senglea, public copy"],
    ["25 Oct 2018", "seismic tsunami", "excursions of some 25 cm at Portomaso", "before installation"],
    ["18 Jun 2019", "milgħuba", "sea bed exposed and quay overtopped in St Paul's Bay", "before installation"],
    ["30 Jun 2022", "milgħuba", "flooding at Marsaskala, St Julian's and Qawra", "no data, record resumes on 1 July"],
    ["1 Jul 2023", "milgħuba", "flooding at Marsaskala and Xemxija", "displaced level, not usable"],
    ["13 Jun 2024", "meteotsunami", "flooding of the main square of Msida", "displaced level, not usable"],
  ], { x: M, y: 2.4, w: 12.09, colW: [1.5, 1.8, 4.9, 3.89], rowH: 0.38 }, () => "left");

  box(s, M, 4.92, 5.95, 1.62, "State of the record",
    "Two windows are provisionally admitted to the analysis, 24 June to 31 December 2021 and 1 December 2022 to 31 March 2023, on monthly coverage and stability of the level. From April 2023 the level appears displaced by some 2 m and the gauge transmits by day only.", false);
  box(s, 6.76, 4.92, 5.95, 1.62, "Consequence for the study",
    "None of the three events since installation is resolved in the public copy, and Portomaso returns no data from the IOC facility on those dates. The archive of the group, sea level and one-minute pressure, would therefore be the record against which the response surface is tested.", true);

  s.addNotes("Sources. University of Malta Newspoint for 2018 and 2019, Newsbook for 2022, MaltaToday for 2023 and 2024, the last citing the Oceanography Malta Research Group. Upward radar echoes from vessels, rain and spray are removed by the lower envelope of the 5 s samples, and episodes of reference offset of 1.3 to 2.1 m are removed before the spectrum is computed. The choice of windows is to be confirmed within the group. The displaced level is compatible with the radar ranging to a vessel or pontoon beneath it, which is a conjecture.");
}

/* ---------------- 8. the domain ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, EXTENT", "Extent over the plateau, and its cost",
    null);
  s.addImage({ path: path.join(FIG, "domain_design.png"), x: M, y: 1.72, w: 12.09, h: 5.42 });
  s.addNotes("Domain B, roughly 86 by 66 km, east to 15 degrees, short of the escarpment. Stopping there is also what keeps sigma layers defensible.");
}

/* ---------------- 9. resolution and layers ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, DISCRETISATION", "Resolution set by the geometry of the inlets",
    "At the estimated fundamental period of the Grand Harbour, some 17 minutes, a long wave in 16 m of water is 12.8 km long (λ = T√(gh)), far longer than any cell. The planform of the inlets is the feature to be resolved.");

  s.addText("Measured channel width", { x: M, y: 2.3, w: 5.5, h: 0.32, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Half the channel length of Marsamxett is narrower than 135 m, and a third narrower than 50 m.", options: { breakLine: true, paraSpaceAfter: 8 } },
    { text: "Four to five cells carry the conveyance of a channel, eight to ten resolve the flow across it.", options: {} },
  ], { x: M, y: 2.68, w: 5.4, h: 1.1, fontSize: 12.5, color: INK, fontFace: BODY,
       lineSpacing: 17, valign: "top", isTextBox: true, margin: 0 });

  const grad = [
    ["Zone", "Cell size"],
    ["Harbour channels narrower than 150 m", "15 m"],
    ["Harbour basins and their mouths", "30 m"],
    ["Within 1 km of the coast", "120 m"],
    ["Within 5 km of the coast", "480 m"],
    ["Open plateau", "1920 m"],
  ];
  s.addTable(grad.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 1, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: 12, fontFace: BODY, valign: "middle", align: j ? "right" : "left",
  } }))), { x: M, y: 3.9, w: 5.4, colW: [3.9, 1.5], rowH: 0.375,
            border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 2.3, w: 6.16, h: 1.62,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("Mesh and time step", { x: 6.85, y: 2.5, w: 5.6, h: 0.3, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("26,766 faces. Under a resonant long wave the time step is 3.7 s, set by the 15 m cells of the channels, which samples that period of some 17 minutes about 280 times. The 10 m of the source data is the floor, and below 15 m a mesh interpolates rather than resolves.",
    { x: 6.85, y: 2.86, w: 5.6, h: 0.95, fontSize: 12, color: INK, fontFace: BODY,
      lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 4.08, w: 6.16, h: 2.05,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Vertical, 12 to 15 sigma layers foreseen", { x: 6.85, y: 4.28, w: 5.6, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The count is set by residence time, not by the seiche, which is barotropic. Fifteen layers give roughly one metre at the bed in the basins.\n", options: { breakLine: true } },
    { text: "Sigma layers are considered defensible because the domain stops short of the escarpment, the plateau gradient being one part in a thousand.", options: {} },
  ], { x: 6.85, y: 4.64, w: 5.6, h: 1.3, fontSize: 12, color: PALE,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "On the wave side, two nested SWAN grids at 1200 and 250 m. The finer agrees with the SWAN downscaling of the group at 1∕500°, arrived at independently.");
  s.addNotes("A question for Deltares concerns whether sigma holds from 15 m to 150 m, or whether a z-sigma hybrid is indicated. The wave nest was sized from the width of the harbour entrances and landed within a quarter of the resolution already in use on this coast, which is an independent check on the choice.");
}

/* ---------------- 10. mesh as built ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, MESH", "Working mesh and its measured cost",
    "Quadtree refinement by zone, built in UTM 33N and transformed to WGS84, accepted by D-Flow FM 2026.01 at rest and under a forced long wave.");

  s.addImage({ path: path.join(FIG, "mesh_v02.png"), x: M, y: 2.3, w: 8.4, h: 3.36 });

  const stats = [
    ["26,766", "faces, of which some 12,000\nin the harbours"],
    ["3.7 s", "time step under a 25-minute wave\nof 0.15 m at the boundary"],
    ["611 s", "wall time per simulated day,\ntwo-dimensional, serial"],
  ];
  stats.forEach((st, i) => {
    const y = 2.3 + i * 1.14;
    s.addText(st[0], { x: 9.4, y, w: 3.3, h: 0.5, fontSize: 25, bold: true,
      color: i === 1 ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: 9.4, y: y + 0.5, w: 3.3, h: 0.5, fontSize: 11.5,
      color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: M, y: 5.8, w: 12.09, h: 1.2,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText([
    { text: "Indicative cost of the campaign. ", options: { bold: true } },
    { text: "The sweep of the long wave in two dimensions is estimated at some 8 h of serial computation. The three-dimensional runs are assumed at 160 simulated days, namely 60 days of renewal for each of two mouth geometries, a length comparable to the renewal times of 32 to 61 days reported for Barcelona and Tarragona (Samper et al., 2022), and some 40 days of validation. They would take of the order of 45 h on 8 MPI processes, uncertain by a factor of two.", options: {} },
  ], { x: M + 0.35, y: 5.9, w: 11.4, h: 1.0, fontSize: 11.5, color: INK,
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addNotes("The left panel shows the face size over the domain and the right panel the two harbours, with the 15 m cells in the channels narrower than 150 m. Coastal zones of 1 km and 5 km cost 37 per cent less than zones of 2 km and 15 km, with the time step and the harbour response unchanged, since the time step is set by the 15 m cells alone. Refinement carried out directly in degrees yields transitions that FM rejects as not orthogonal, which is why the mesh is built in UTM. Open matters are one edge at 0.553 in the meshkernel orthogonality measure, 1,050 shore faces with a bed at or above zero, and the gaps of the 10 m grid at the heads of Msida and Pietà Creeks.");
}

/* ---------------- 11. open boundary ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, OPEN BOUNDARY", "Reflection of the open boundary under a synthetic pulse",
    "An idealised test, with a Gaussian hump of water level released on a flat bed at 150 m with 1500 m cells and each case compared against a reference domain without a boundary.");

  s.addImage({ path: path.join(FIG, "riemann_pulse_test.png"), x: M, y: 2.3, w: 6.15, h: 4.3 });

  table(s, [
    ["Reflected amplitude", "Riemann", "Prescribed level"],
    ["Normal incidence, channel", "0.3 to 1.3 %", "94 to 100 %"],
    ["Incidence up to 30°, basin", "5 to 9 %", "96 to 98 %"],
    ["Corner cells", "24 to 29 %", "103 %"],
  ], { x: 7.05, y: 2.3, w: 5.66, colW: [2.66, 1.4, 1.6], rowH: 0.38 });

  box(s, 7.05, 3.96, 5.66, 1.4, "Working configuration",
    "A Riemann boundary on all open sides, its corners more than 40 km from the harbours, written as one polyline since FM reads only the first polyline of a boundary file.", true);
  box(s, 7.05, 5.5, 5.66, 1.1, "Cases to be tested before production",
    "A residual current across the boundary, a non-zero incoming signal from CMEMS, variable depth along the boundary, and Coriolis.", false);

  s.addNotes("Panels, from the upper left. The record in the channel, where the prescribed level returns the pulse inverted and almost undiminished while the Riemann record follows the reference. A boundary cell of the square basin at 22.5 degrees. The reflection coefficient against incidence angle, with first-order theory dashed. The volume retained in the basin, which the prescribed level holds as a trapped mode. The reflected wave is the difference between each case and the reference, so incident and reflected waves need not be separated in time. The Riemann condition assumes a plane wave at normal incidence over a fluid at rest, which is why the four production cases remain to be tested. Laksono et al. (2026) apply the same boundary over the Sicilian Channel for the same reason.");
}

/* ---------------- 12. prior work and setting ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "PRIOR WORK AND SETTING", "Existing work and the scope of the present study",
    "The Grand Harbour has been modelled before, and the group operates a forecasting system over the same waters.");

  s.addText("The two studies that bear on the site", { x: M, y: 2.3, w: 5.9, h: 0.32,
    fontSize: 14, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Mazas and Farrugia, ARTELIA and Infrastructure Malta. ", options: { bold: true, breakLine: false } },
    { text: "The Grand Harbour modelled for wind-wave agitation in PHAROS, against a directional climate hindcast from 1992 to 2019. Damage in the port documented for the storms of February 2019 and February 2023.\n", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "Drago (2018), the design report of the group. ", options: { bold: true, breakLine: false } },
    { text: "A relocatable model setup is requested for ad hoc local domains, and harbour flushing at the five principal harbours appears among the process-model targets, with the Deltares suite among the families to review.", options: {} },
  ], { x: M, y: 2.7, w: 5.9, h: 2.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16.5, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.95, y: 2.3, w: 5.76, h: 3.32,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Operational system of the group", { x: 7.25, y: 2.52, w: 5.2, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "ROSARIO, Princeton Ocean Model, 1∕64° and 1∕96°, nested into CMEMS.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "SWAN downscaled to the embayments at 1∕500°, about 200 m.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "ROSARIO-SHYFEM, unstructured, three-dimensional, operational to a four-day forecast, from a few kilometres to 50 m at the coast, with Lagrangian particle tracking.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "Boundary conditions derived from CMEMS, as in the present work.", options: { bullet: true } },
  ], { x: 7.25, y: 2.9, w: 5.2, h: 2.55, fontSize: 11.5, color: PALE,
       fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: M, y: 5.82, w: 12.09, h: 0.92,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText([
    { text: "The present work is a process study conducted within the group, alongside the operational system. ", options: {} },
    { text: "It differs in the resolution inside the basins, 15 to 30 m against 50 m, in the coupling to a spectral wave model, and in the frequency band it addresses.", options: {} },
  ], { x: M + 0.35, y: 5.99, w: 11.4, h: 0.62, fontSize: 12, color: INK,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("The relocatability requirement of the design report corresponds to the framework-transfer argument of the thesis, and the porting log is the evidence for it. The study complements the operational system in a band and at a resolution the forecasting configuration is not designed for.");
}

/* ---------------- 13. the questions ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "RESEARCH QUESTIONS", "Principal question and three accompanying questions",
    "Proposed formulation, submitted to the group for discussion.");

  s.addShape(p.ShapeType.roundRect, { x: M, y: 2.3, w: 12.09, h: 1.35,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Principal, attribution of amplification", { x: M + 0.35, y: 2.42, w: 8, h: 0.3,
    fontSize: 13.5, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Of the amplification between the open sea and the heads of the Valletta harbours, how is it partitioned between Proudman resonance over the plateau, shoaling on the approach, and resonance of the basins, and which disturbance speeds and directions maximise that chain?",
    { x: M + 0.35, y: 2.76, w: 11.4, h: 0.8, fontSize: 13.5, italic: true, color: WHITE,
      fontFace: HEAD, lineSpacing: 19, valign: "top", isTextBox: true, margin: 0 });

  const acc = [
    ["Applied", "Which parts of the harbour system amplify most, and which geometric features control that?",
     "Expected output, a map of exposure by inlet and by quay."],
    ["Renewal of harbour water", "What renews the water of a microtidal harbour, and how much of the exchange driven by long waves is renewal rather than reversible oscillation?",
     "Expected output, residence times from three-dimensional and Lagrangian runs."],
    ["Geometry of the mouth", "How sensitive are the long-wave response and the renewal to the geometry of the mouth?",
     "A sensitivity on the class of basin, representing no particular design. A first estimate gives a lengthening of the mode by 1.5 to 4 per cent for a restriction of a quarter."],
  ];
  acc.forEach((a, i) => {
    const x = M + i * 4.12;
    s.addShape(p.ShapeType.roundRect, { x, y: 3.9, w: 3.85, h: 2.55,
      fill: { color: TINT }, rectRadius: 0.06 });
    s.addText(a[0], { x: x + 0.28, y: 4.05, w: 3.3, h: 0.32, fontSize: 13.5,
      bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(a[1], { x: x + 0.28, y: 4.42, w: 3.3, h: 0.95, fontSize: 12, italic: true,
      color: INK, fontFace: HEAD, lineSpacing: 16, valign: "top", isTextBox: true, margin: 0 });
    s.addText(a[2], { x: x + 0.28, y: 5.4, w: 3.3, h: 0.95, fontSize: 11,
      color: MUTED, fontFace: BODY, lineSpacing: 14.5, valign: "top", isTextBox: true, margin: 0 });
  });

  note(s, "The principal question requires a model, since no arrangement of gauges separates the three stages, and it addresses the generation of the wave, which the published work appears to leave open.");
  s.addNotes("The accompanying questions depend on the principal one and are ordered by that dependence. The renewal question has independent standing under the Water Framework Directive and exercises the three-dimensional and Lagrangian components of the framework. The question on the mouth is retained only if the group considers it appropriate, given the public project on the Grand Harbour entrance. On the measured profile its effect on the mode is of the same order as a metre of sea level rise, 3.1 per cent, while the Helmholtz scaling would overstate it by a factor of three to ten, and the effect on exchange is expected to be the larger one.");
}

/* ---------------- 14. the design ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "EXPERIMENTAL DESIGN", "Sweep for the long wave, hindcast for validation",
    "ERA5 does not resolve the atmospheric gravity waves associated with the milgħuba, so the long wave is studied by a sweep of idealised disturbances, while circulation, sea level and waves are validated by a conventional hindcast.");

  table(s, [
    ["Proposed sweep", ""],
    ["Forcing", "moving pressure disturbance of fixed amplitude"],
    ["Speed", "6 values bracketing 94 to 155 km h⁻¹"],
    ["Direction", "8, at intervals of 45°"],
    ["Width", "2"],
    ["Scenarios", "96, of 12 simulated hours each"],
    ["Configuration", "two-dimensional, barotropic, without wave coupling"],
    ["Output", "sea level at one minute at the inlets and the gauges"],
    ["Indicative cost", "some 8 h of serial computation"],
  ], { x: M, y: 2.4, w: 6.3, colW: [1.9, 4.4], rowH: 0.4, fontSize: 11.5 }, () => "left");

  box(s, 7.2, 2.4, 5.51, 1.62, "Requirements of the sweep",
    "A pressure field varying in space and time imposed in D-Flow FM, the weakly reflective boundary of the preceding slide, and a response close to linear in the amplitude of the disturbance, which is to be verified.", false);
  box(s, 7.2, 4.18, 5.51, 1.98, "Hindcast and test against events",
    "A hindcast of some 40 days in three dimensions, forced by CMEMS and ERA5 with wave coupling, would validate sea level, currents and waves. The dated milgħuba events would then be located on the response surface through their one-minute pressure records, to examine whether they occur under the conditions identified as resonant.", true);

  note(s, "The response surface would be a property of the geometry, so projected changes in the forcing could be applied to it without running climate scenarios through the model.");
  s.addNotes("The sweep is two-dimensional because the long wave is barotropic, its wavelength being hundreds of times the depth, so a depth-averaged model carries it and the vertical structure adds cost without adding to the answer. Three dimensions are reserved for the hindcast and for renewal, where stratification and vertical shear matter. The number of speeds, directions and widths is a proposal sized for cost, 96 scenarios of half a simulated day, and is open to revision. A repetition over a modified mouth would double it. The validation hindcast draws on the BLUE buoy, the HF radar and the tide gauges, and Storm Harry of January 2026 is a candidate case.");
}

/* ---------------- 15. open questions ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OPEN QUESTIONS", "Open questions for the continuation", null);

  questions(s, [
    ["Sea level and one-minute pressure from the archive of the group on the dates of the events",
     "Senglea and Delimara for 29 June to 2 July 2022, 30 June to 2 July 2023 and 12 to 14 June 2024, with PORTO pressure at Elmo, Kordin and Msida. The public records resolve none of the three."],
    ["History of the Senglea installation, and Portomaso at one minute",
     "Confirmation of the windows admitted and the cause of the displacement from April 2023. A gauge outside both basins would help separate the readings of the 23-minute peak."],
    ["Appropriateness of the sensitivity exercise on the harbour mouth",
     "The exercise is a response curve over the class of basin and carries no assessment of the project in consultation. The present geometry of the entrance, the Ricasoli arm in particular, bears on the estimate."],
    ["Prior work on the generation of the wave",
     "Published work imposes the long wave at the offshore boundary. Unpublished material may have treated its generation over the shelf, in which case the question would be reformulated."],
    ["Elements of ROSARIO-SHYFEM to be reflected in the configuration",
     "The treatment of the open boundary and the bathymetry inside the harbours, in particular at the heads of Msida and Pietà Creeks, where the 10 m grid has gaps."],
    ["Data for validation",
     "Currents and stratification inside the harbours, waves beyond the BLUE buoy, the levelling datum of the bathymetry against the gauge zeros, and Storm Harry, January 2026, as a possible case."],
  ], 2.05, 1.62, 0.98);

  s.addNotes("The first two determine whether the response surface can be tested against events at all. The remainder shape the scope and the configuration.");
}

/* ---------------- 16. sequence ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  // A veil over the photograph that copy_deck_cover.ps1 places behind this
  // slide, so that the text keeps its contrast.
  s.addShape(p.ShapeType.rect, { x: 0, y: 0, w: W, h: H,
    fill: { color: MID, transparency: 30 }, line: { color: MID, transparency: 100 } });
  s.addShape(p.ShapeType.ellipse, { x: -1.9, y: 4.2, w: 5.2, h: 5.2,
    fill: { color: BLUE, transparency: 60 } });

  s.addText("SEQUENCE", { x: M, y: 0.7, w: 9, h: 0.3, fontSize: 12,
    bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Planned sequence to the first production runs", { x: M, y: 1.05, w: 11, h: 0.7, fontSize: 30,
    bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });

  const tl = [
    ["To date", "First-order basin modes, pulse test of the boundary, Senglea spectrum, working mesh."],
    ["October", "Boundary tests under pressure forcing, pilot scenario and impulse response, then the sweep of the long wave, barotropic and two-dimensional."],
    ["19 October", "Delft3D User Days abstract."],
    ["2 to 4 November", "Delft3D User Days at Deltares, with the configuration questions."],
    ["November", "Three-dimensional runs of the validation hindcast and of renewal, after a first test run in October."],
  ];
  // The timeline occupies the left column only, so the panel on the right has
  // its own band.
  tl.forEach((t, i) => {
    const y = 2.15 + i * 0.92;
    s.addShape(p.ShapeType.ellipse, { x: M + 0.05, y: y + 0.1, w: 0.17, h: 0.17,
      fill: { color: i === 2 ? ORANGE : PALE } });
    s.addText(t[0], { x: M + 0.45, y, w: 2.2, h: 0.33, fontSize: 13, bold: true,
      color: i === 2 ? ORANGE : WHITE, fontFace: BODY, valign: "top", isTextBox: true, margin: 0 });
    s.addText(t[1], { x: M + 2.7, y, w: 4.0, h: 0.8, fontSize: 12,
      color: "DCE7F5", fontFace: BODY, lineSpacing: 15, valign: "top", isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: 7.5, y: 2.15, w: 5.21, h: 3.4,
    fill: { color: BLUE, transparency: 30 }, rectRadius: 0.06 });
  s.addText("Beyond the period", { x: 7.8, y: 2.38, w: 4.6, h: 0.3, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The Stagnone twin runs containerised on the EDITO Datalab and publishes to its object storage.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "A Valletta configuration could take the same route, should it prove stable in time, so that the deliverable would be a running pilot.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "This would correspond to the relocatable setup requested in the design report of the group.", options: { bold: true, color: WHITE } },
  ], { x: 7.8, y: 2.78, w: 4.6, h: 2.5, fontSize: 11.5, color: "DCE7F5",
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addText([
    { text: "Documents, figures and the reproducible analysis: ", options: { italic: true } },
    { text: "github.com/cicero-martins/MaltaDT", options: { bold: true, color: WHITE,
      hyperlink: { url: "https://github.com/cicero-martins/MaltaDT" } } },
  ], { x: M, y: 6.78, w: 9.0, h: 0.3, fontSize: 11.5, color: PALE,
       fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("The broadband impulse yields the modal structure of the harbours on the mesh, which decides between the two readings of the 23-minute peak. The remaining boundary tests are the residual current, the non-zero incoming signal from CMEMS and a pressure disturbance crossing the boundary. The sweep precedes the three-dimensional runs because it needs only the mesh, the boundary and the pressure field, whereas those runs need the full forcing chain. A few scenarios on a larger domain would show whether the extent truncates the Proudman stage. The bathymetry at the heads of Msida and Pietà Creeks is to be completed before the inlets are relied upon. The block of 27 October to 21 November loses four working days to Delft and holds fifteen rather than nineteen. The EDITO deployment is conditional on the configuration proving stable in time, and it belongs to the last block of the period alongside the integration into the ocean.mt portal.");
}

p.writeFile({ fileName: OUT }).then(() => console.log("written", OUT));
