// Deck: Valletta harbour system, model concept and the questions to settle.
// Built for the meeting with the Oceanography Malta Research Group, September 2026.
//
// Requires pptxgenjs, which is not part of the project environment. Install it
// in a scratch directory and run from there rather than adding node_modules to
// the repository:
//     npm install pptxgenjs && node build_concept_deck.js out.pptx
//
// Neither LibreOffice nor PowerPoint automation is available here, so the deck
// cannot be rendered for a visual pass. Geometry and text fit were checked
// analytically instead, and the figures it embeds are generated by
// figure_bathymetry_overview.py and figure_domain_design.py.
const pptx = require("pptxgenjs");
const path = require("path");

const FIG = "C:/Users/Unipa/Documents/MaltaDT/figures";
const OUT = process.argv[2] || "valletta_model_concept.pptx";

// Palette. Deep blue dominates; orange is the single accent and matches the
// figures, so the slides and the plots read as one set.
const MID = "21295C";
const BLUE = "065A82";
const TEAL = "1C7293";
const ORANGE = "EB6834";
const WHITE = "FFFFFF";
const INK = "1A1A1A";
const MUTED = "5F6368";
const TINT = "EEF3F6";

const HEAD = "Cambria";
const BODY = "Calibri";

const p = new pptx();
p.layout = "LAYOUT_WIDE"; // 13.33 x 7.5
p.author = "Cicero Martins Jr";
p.title = "Valletta harbour system: model concept";

const W = 13.33, H = 7.5, M = 0.62;

function titleSlide(s, kicker, title, sub) {
  s.addText(kicker, { x: M, y: 0.48, w: 9, h: 0.3, fontSize: 12, bold: true,
    color: ORANGE, fontFace: BODY, charSpacing: 2, isTextBox: true, margin: 0 });
  s.addText(title, { x: M, y: 0.82, w: 11.4, h: 0.72, fontSize: 32, bold: true,
    color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
  if (sub) s.addText(sub, { x: M, y: 1.54, w: 11.9, h: 0.64, fontSize: 14,
    color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
}

function badge(s, n, x, y, col) {
  s.addShape(p.ShapeType.ellipse, { x, y, w: 0.44, h: 0.44, fill: { color: col } });
  s.addText(String(n), { x, y, w: 0.44, h: 0.44, fontSize: 15, bold: true,
    color: WHITE, align: "center", valign: "middle", fontFace: BODY, isTextBox: true, margin: 0 });
}

function note(s, txt) {
  s.addText(txt, { x: M, y: H - 0.88, w: W - 2 * M, h: 0.34, fontSize: 10.5,
    color: MUTED, italic: true, fontFace: BODY, isTextBox: true, margin: 0 });
}

/* ---------------- 1. title ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  s.addShape(p.ShapeType.ellipse, { x: 9.3, y: -1.4, w: 5.6, h: 5.6,
    fill: { color: BLUE, transparency: 55 } });
  s.addShape(p.ShapeType.ellipse, { x: 11.0, y: 3.4, w: 2.6, h: 2.6,
    fill: { color: ORANGE, transparency: 70 } });

  s.addText("WETWISE · WP3 · Maltese pilot", { x: M, y: 1.5, w: 8.4, h: 0.3,
    fontSize: 12, bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY,
    isTextBox: true, margin: 0 });
  s.addText("The Valletta harbour system", { x: M, y: 1.95, w: 8.6, h: 0.95,
    fontSize: 40, bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Model concept, and the questions to settle", { x: M, y: 2.95, w: 8.6,
    h: 0.5, fontSize: 19, color: "CADCFC", fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Cicero Martins Jr", options: { bold: true, color: WHITE } },
    { text: "   Università degli Studi di Palermo", options: { color: "9FB3D1" } },
  ], { x: M, y: 4.35, w: 8.6, h: 0.3, fontSize: 13, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Research period at the Oceanography Malta Research Group, University of Malta",
    { x: M, y: 4.68, w: 8.6, h: 0.3, fontSize: 12, color: "9FB3D1", fontFace: BODY,
      isTextBox: true, margin: 0 });
  s.addText("25 September 2026", { x: M, y: 5.02, w: 8.6, h: 0.3, fontSize: 12,
    color: "9FB3D1", fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("The deck covers the intended model and the matters to be settled before its construction.");
}

/* ---------------- 2. where this starts ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "ORIGIN", "A framework, carried across archetype",
    "The solver and the assembly are unchanged, while the governing physics differs.");

  s.addText([
    { text: "The framework originates in the Stagnone di Marsala digital twin, a coupled Delft3D FM and SWAN model of a shallow vegetated lagoon.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "A transfer to a second lagoon would remain within a single archetype and would establish little. A transfer to a deep engineered harbour establishes whether the pipeline is reusable or was fitted to one site.", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "The stages that transfer constitute the reuse. Those that do not constitute a finding about where the generality of the framework ends, and they are recorded as such.", options: {} },
  ], { x: M, y: 2.25, w: 5.7, h: 3.0, fontSize: 14.5, color: INK, fontFace: BODY,
       lineSpacing: 22, isTextBox: true, margin: 0 });

  const rows = [
    ["", "Stagnone", "Valletta"],
    ["Depth", "sub-metre", "12 to 20 m"],
    ["Bed", "seagrass canopy", "engineered, quay walls"],
    ["Boundary signal", "tide", "long wave, atmospheric"],
    ["Circulation driver", "wind", "the same long wave"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => ({
    text: c,
    options: {
      bold: i === 0 || j === 0,
      color: i === 0 ? WHITE : INK,
      fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
      fontSize: 12.5, fontFace: BODY, valign: "middle",
    },
  }))), { x: 6.85, y: 2.25, w: 5.86, colW: [1.86, 2.0, 2.0], rowH: 0.46,
          border: { type: "solid", color: "D6DEE3", pt: 0.5 } });

  note(s, "The transfer effort is logged stage by stage as transferred, re-parameterised or not applicable. That log constitutes the methodological result.");
  s.addNotes("Context. The thesis contribution is framework reusability, and Valletta constitutes the harder test.");
}

/* ---------------- 3. data in hand ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "AVAILABLE DATA", "Bathymetry and coastline, co-registered",
    "Supplied by the host group on 22 and 23 September.");

  const stats = [
    ["10 m", "merged LiDAR and sonar,\nCDI 4036_MEPA"],
    ["174 to 256×", "more resolved water cells\nthan the public product"],
    ["99.5 %", "land and water agreement\nwith the coastline"],
  ];
  stats.forEach((st, i) => {
    const y = 2.25 + i * 1.28;
    s.addText(st[0], { x: M, y, w: 2.5, h: 0.52, fontSize: 27, bold: true,
      color: i === 1 ? ORANGE : BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: M, y: y + 0.52, w: 3.4, h: 0.6, fontSize: 12,
      color: MUTED, fontFace: BODY, isTextBox: true, margin: 0 });
  });

  s.addImage({ path: path.join(FIG, "bathymetry_overview.png"),
    x: 4.55, y: 1.95, w: 5.2, h: 4.44 });
  s.addText([
    { text: "Two coordinate reference conditions\n", options: { bold: true, color: INK, breakLine: true } },
    { text: "The grids do not encode their datum. Interpreted as WGS84 they are displaced by 197 m, and no error is raised.\n", options: { color: MUTED, breakLine: true } },
    { text: "The bathymetry is ED50 and the coastline is WGS84, so neither overlays the other without a datum transformation.", options: { color: MUTED } },
  ], { x: 10.05, y: 2.6, w: 2.7, h: 2.2, fontSize: 11.5, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "Grand Harbour 1.64 km², mean depth 15.9 m. Marsamxett 1.32 km², mean depth 13.3 m.");
  s.addNotes("The 10 m data came from the group's own contribution to EMODnet. The public product gives the inlets one to three cells.");
}

/* ---------------- 4. the phenomenon ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "THE PHENOMENON", "The milgħuba is a meteotsunami",
    "An atmospherically generated long wave, known as rissaga in the Balearics and as marrobbio on the Sicilian shelf.");

  const stages = [
    ["Proudman resonance", "Energy transfers most efficiently when the atmospheric disturbance travels at the celerity of the long wave beneath it.",
     "The Malta Plateau, 99 to 190 m, is resonant with disturbances of 94 to 155 km h⁻¹."],
    ["Shoaling", "Green's law governs the amplification of the wave over the shoaling approach.",
     "From the plateau into the harbours, a factor of 1.75 to 1.84."],
    ["Basin resonance", "The geometry of the basin amplifies the wave arriving at its mouth.",
     "Quarter-wave and Helmholtz estimates agree at 12 to 18 minutes."],
  ];
  stages.forEach((st, i) => {
    const x = M + i * 4.12;
    s.addShape(p.ShapeType.roundRect, { x, y: 2.72, w: 3.85, h: 2.5,
      fill: { color: TINT }, rectRadius: 0.06 });
    badge(s, i + 1, x + 0.28, 2.42, i === 0 ? ORANGE : BLUE);
    s.addText(st[0], { x: x + 0.28, y: 3.05, w: 3.3, h: 0.36, fontSize: 15.5,
      bold: true, color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: x + 0.28, y: 3.44, w: 3.3, h: 0.82, fontSize: 12,
      color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(st[2], { x: x + 0.28, y: 4.32, w: 3.3, h: 0.8, fontSize: 11,
      color: TEAL, bold: true, fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });
  });

  note(s, "At Ciutadella, Menorca, the three compound to an order of magnitude. No equivalent decomposition has been published for Malta.");
  s.addNotes("The three-stage chain organises the study and determines the domain.");
}

/* ---------------- 5. the pivotal measurement ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "RESONANT PERIODS", "The harbours do not resonate in the observed band",
    "Quarter-wave periods, T = 4L∕√(gh), against the 0.2 to 2 cph band reported by Drago.");

  const rows = [
    ["Element", "L", "h", "Period", "Frequency", ""],
    ["Plateau to Sicily, quarter wave", "90 km", "150 m", "156 min", "0.38 cph", "within"],
    ["Plateau to Sicily, half wave", "90 km", "150 m", "78 min", "0.77 cph", "within"],
    ["Near plateau", "25 km", "120 m", "49 min", "1.24 cph", "within"],
    ["Grand Harbour", "3.2 km", "16 m", "17 min", "3.49 cph", "outside"],
    ["Marsamxett", "3.2 km", "13 m", "18 min", "3.26 cph", "outside"],
    ["A 1 km inlet", "1.0 km", "12 m", "6 min", "9.76 cph", "outside"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => {
    const head = i === 0;
    const inBand = c === "within";
    return { text: c, options: {
      bold: head || j === 0 || inBand,
      color: head ? WHITE : (inBand ? ORANGE : (c === "outside" ? MUTED : INK)),
      fill: { color: head ? BLUE : (i <= 3 ? "FDF0E9" : WHITE) },
      fontSize: 12, fontFace: BODY, valign: "middle",
      align: j === 0 ? "left" : (j === 5 ? "left" : "right"),
    } };
  })), { x: M, y: 2.5, w: 8.5, colW: [3.0, 0.95, 0.85, 1.05, 1.15, 1.5], rowH: 0.375,
         border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 9.45, y: 2.5, w: 3.26, h: 2.66,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("The consequence", { x: 9.75, y: 2.75, w: 2.7, h: 0.32, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The harbours respond to a shelf-scale oscillation rather than generating one.\n", options: { breakLine: true } },
    { text: "A domain confined to the harbours holds no resonator in the band, and the available boundary product carries no energy there.\n", options: { breakLine: true } },
    { text: "The domain is therefore required to contain the plateau.", options: { bold: true, color: WHITE } },
  ], { x: 9.75, y: 3.15, w: 2.7, h: 1.9, fontSize: 11.5, color: "CADCFC",
       fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });

  note(s, "A Helmholtz idealisation returns 12 to 18 minutes likewise. The 1910 breakwater partly closes the entrance, which lengthens the period, so the figure awaits the mesh.");
  s.addNotes("The estimate was tested against its two plausible failures, the Helmholtz idealisation and excitation below resonance. The domain follows from this table. One correction is outstanding and it is not conservative: the coastline carries the St Elmo breakwater as a detached polygon of 378 m, so the mouth is not the single 400 m opening assumed, and a smaller section lengthens the period toward the observed band. Whether the group's harbour records carry energy near 17 minutes is the first outstanding question.");
}

/* ---------------- 6. the domain ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, EXTENT", "Extent over the plateau, and its cost",
    null);
  s.addImage({ path: path.join(FIG, "domain_design.png"), x: M, y: 1.72, w: 12.09, h: 5.42 });
  s.addNotes("Domain B, roughly 86 by 66 km, east to 15 degrees, short of the escarpment. Stopping there is also what keeps sigma layers defensible.");
}

/* ---------------- 7. resolution and layers ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "MODEL CONCEPT, DISCRETISATION", "The geometry sets the resolution",
    "A 17-minute wave in 16 m of water is 12.8 km long. The planform of the inlets is what must be resolved.");

  s.addText("Measured channel width", { x: M, y: 2.3, w: 5.5, h: 0.32, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Half the channel length of Marsamxett is narrower than 135 m, and a third narrower than 50 m.\n", options: { breakLine: true, paraSpaceAfter: 8 } },
    { text: "Four to five cells carry the conveyance of a channel, eight to ten resolve the flow across it.", options: {} },
  ], { x: M, y: 2.68, w: 5.4, h: 0.95, fontSize: 12.5, color: INK, fontFace: BODY,
       lineSpacing: 17, isTextBox: true, margin: 0 });

  const grad = [
    ["Zone", "Target"],
    ["Inlets and entrances", "15 m"],
    ["Harbour basins", "30 m"],
    ["Nearshore, within 2 km", "100 m"],
    ["Coastal, 2 to 15 km", "300 m"],
    ["Open plateau", "1500 m"],
  ];
  s.addTable(grad.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 1, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: 12, fontFace: BODY, valign: "middle", align: j ? "right" : "left",
  } }))), { x: M, y: 3.78, w: 5.4, colW: [3.6, 1.8], rowH: 0.375,
            border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 2.3, w: 6.16, h: 1.62,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("Mesh and time step", { x: 6.85, y: 2.5, w: 5.6, h: 0.3, fontSize: 14,
    bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Approximately 28,500 cells. A time step of 6 to 12 s at Courant 5 to 10 in the finest cells, which samples a 17-minute wave about a hundred times per cycle. The 10 m of the source data is the floor; below 15 m a mesh interpolates rather than resolves.",
    { x: 6.85, y: 2.86, w: 5.6, h: 0.95, fontSize: 12, color: INK, fontFace: BODY,
      lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.55, y: 4.08, w: 6.16, h: 2.05,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Vertical, 12 to 15 sigma layers", { x: 6.85, y: 4.28, w: 5.6, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The count is set by residence time, not by the seiche, which is barotropic. Fifteen layers give roughly one metre at the bed in the basins.\n", options: { breakLine: true } },
    { text: "Sigma is defensible only because the domain stops short of the escarpment, where the plateau gradient is one part in a thousand.", options: {} },
  ], { x: 6.85, y: 4.64, w: 5.6, h: 1.3, fontSize: 12, color: "CADCFC",
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  note(s, "On the wave side, two nested SWAN grids at 1200 and 250 m. The finer agrees with the group's own downscaling at 1∕500°, arrived at independently.");
  s.addNotes("A question for Deltares concerns whether sigma holds from 15 m to 150 m, or whether a z-sigma hybrid is indicated. The wave nest was sized from the width of the harbour entrances and landed within a quarter of the resolution the group already uses on this coast, which is an independent check on the choice.");
}

/* ---------------- 8. prior work and setting ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "PRIOR WORK AND SETTING", "What exists, and what it leaves untreated",
    "The Grand Harbour has been modelled before, and the host group operates a forecasting system over the same waters.");

  s.addText("The two studies that bear on the site", { x: M, y: 2.3, w: 5.9, h: 0.32,
    fontSize: 14, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Mazas and Farrugia, ARTELIA and Infrastructure Malta. ", options: { bold: true, breakLine: false } },
    { text: "The Grand Harbour modelled for wind-wave agitation in PHAROS, against a directional climate hindcast from 1992 to 2019. Damage in the port documented for the storms of February 2019 and February 2023.\n", options: { breakLine: true, paraSpaceAfter: 10 } },
    { text: "Drago, 2018, the design report of the host group. ", options: { bold: true, breakLine: false } },
    { text: "A relocatable model setup is requested for ad hoc local domains, and harbour flushing at the five principal harbours appears among the process-model targets, with the Deltares suite among the families to review.", options: {} },
  ], { x: M, y: 2.7, w: 5.9, h: 2.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16.5, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 6.95, y: 2.3, w: 5.76, h: 3.32,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Operated by the host group", { x: 7.25, y: 2.52, w: 5.2, h: 0.3,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "ROSARIO, Princeton Ocean Model, 1∕64° and 1∕96°, nested into CMEMS.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "SWAN downscaled to the embayments at 1∕500°, about 200 m.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "ROSARIO-SHYFEM, unstructured, three-dimensional, operational to a four-day forecast, from a few kilometres to 50 m at the coast, with Lagrangian particle tracking.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
    { text: "Boundary conditions derived from CMEMS, which is what this project does also.", options: { bullet: true } },
  ], { x: 7.25, y: 2.9, w: 5.2, h: 2.55, fontSize: 11.5, color: "CADCFC",
       fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: M, y: 5.82, w: 12.09, h: 0.92,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText([
    { text: "The present work is an independent exercise for the research period. ", options: { bold: true } },
    { text: "It differs in the resolution inside the basins, 15 to 30 m against 50 m, in the coupling to a spectral wave model, and in the frequency band it addresses.", options: {} },
  ], { x: M + 0.35, y: 5.99, w: 11.4, h: 0.62, fontSize: 12, color: INK,
       fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("Nothing here is claimed as a capability the group lacks. The relocatability requirement in the design report corresponds to the framework-transfer argument of the thesis, and the porting log is the evidence for it.");
}

/* ---------------- 9. the question ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "RESEARCH QUESTION", "A proposed question, for the group to judge",
    "Drafted this week and put to the group before it is committed to.");

  s.addShape(p.ShapeType.roundRect, { x: M, y: 2.34, w: 12.09, h: 1.42,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("Of the amplification between the open sea and the heads of the Valletta harbours, how is it partitioned between Proudman resonance over the plateau, shoaling on the approach, and resonance of the basins themselves, and which atmospheric disturbance speeds and directions maximise that chain?",
    { x: M + 0.35, y: 2.57, w: 11.4, h: 1.0, fontSize: 15, italic: true, color: INK,
      fontFace: HEAD, lineSpacing: 21, isTextBox: true, margin: 0 });

  s.addText("Basis for the formulation", { x: M, y: 4.07, w: 5.7, h: 0.32,
    fontSize: 14, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "It is framed so that answering it requires a model. No arrangement of gauges separates the three stages of amplification from one another.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "It is framed so that it does not repeat the prior work, which treats the response of a basin to a wave already present at its boundary.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "Should the group judge the standing of that prior work differently, the formulation changes with it.", options: { bullet: true } },
  ], { x: M, y: 4.45, w: 5.7, h: 1.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addText("What the prior work already covers", { x: 6.95, y: 4.07, w: 5.7, h: 0.32,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Maltese coastal seiches were modelled in 2007, in a two-dimensional depth-averaged POM, for Mellieħa and St Paul's Bay, forced by a prescribed offshore long wave.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "The Grand Harbour itself was modelled by ARTELIA in PHAROS, for wind-wave agitation, against a directional climate hindcast from 1992 to 2019.", options: { bullet: true, breakLine: true, paraSpaceAfter: 7 } },
    { text: "What neither treats is the generation of the long wave, the circulation of the harbour, or its renewal.", options: { bullet: true } },
  ], { x: 6.95, y: 4.45, w: 5.76, h: 1.9, fontSize: 12, color: INK, fontFace: BODY,
       lineSpacing: 16, isTextBox: true, margin: 0 });

  s.addNotes("The question is a proposal rather than a decision. Whether the group has work of its own planned on the generation side, and how the effort would then be divided, should be put to them directly. The applied companion is a map of exposure by inlet and quay, and the renewal question, treated on the following slides, has independent standing under the Water Framework Directive.");
}

/* ---------------- 10. sensitivity of the mouth ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "A SECOND QUESTION", "The basin is sensitive to the geometry of its mouth",
    "An academic sensitivity on the class of basin, put to the group for judgement. No particular design is represented.");

  const rows = [
    ["Restriction of the mouth section", "Pumping period", "Grand Harbour"],
    ["none", "reference", "12.4 to 17.5 min"],
    ["25 per cent", "+15.5 %", "14.3 to 20.2 min"],
    ["50 per cent", "+41.4 %", "17.5 to 24.7 min"],
    ["66 per cent", "+71.5 %", "21.2 to 30.0 min"],
  ];
  s.addTable(rows.map((r, i) => r.map((c, j) => ({ text: c, options: {
    bold: i === 0 || j === 0, color: i === 0 ? WHITE : INK,
    fill: { color: i === 0 ? BLUE : (i % 2 ? WHITE : TINT) },
    fontSize: 12, fontFace: BODY, valign: "middle", align: j ? "right" : "left",
  } }))), { x: M, y: 2.5, w: 7.1, colW: [3.1, 2.2, 1.8], rowH: 0.4,
            border: { type: "solid", color: "E2E8EC", pt: 0.5 } });

  s.addText("The period scales as the inverse square root of the open cross-section, so the shift is independent of basin area and of the length of the channel. Exchange scales with the section directly, and responds more strongly still.",
    { x: M, y: 4.62, w: 7.1, h: 0.8, fontSize: 11.5, color: MUTED, fontFace: BODY,
      lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 8.05, y: 2.5, w: 4.66, h: 1.72,
    fill: { color: TINT }, rectRadius: 0.06 });
  s.addText("The magnitude in context", { x: 8.35, y: 2.68, w: 4.1, h: 0.3,
    fontSize: 13.5, bold: true, color: BLUE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("A metre of sea level rise displaces these modes by one to four per cent. A restriction of a quarter displaces them four times as far. The geometry of the mouth is the dominant control.",
    { x: 8.35, y: 3.04, w: 4.1, h: 1.05, fontSize: 11.5, color: INK, fontFace: BODY,
      lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addShape(p.ShapeType.roundRect, { x: 8.05, y: 4.38, w: 4.66, h: 1.72,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("The limit of the result", { x: 8.35, y: 4.56, w: 4.1, h: 0.3,
    fontSize: 13.5, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText("Reaching the observed band would require the mouth to lose two thirds of its section. The conclusion that the harbours respond rather than resonate stands.",
    { x: 8.35, y: 4.92, w: 4.1, h: 1.05, fontSize: 11.5, color: "CADCFC", fontFace: BODY,
      lineSpacing: 15.5, isTextBox: true, margin: 0 });

  note(s, "The cost is a second evaluation of the same sweep, with no new forcing, no new validation and no new configuration.");
  s.addNotes("The framing is a response curve over the class of basin. The exact geometry of any proposed structure is neither needed nor used, and the exercise carries no assessment of the project now in consultation. Whether to pursue it at all is the first of the outstanding questions.");
}

/* ---------------- 11. the design ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "EXPERIMENTAL DESIGN", "A parametric sweep in place of a hindcast",
    "ERA5 does not resolve the atmospheric gravity waves that trigger the phenomenon, which has constituted the largest standing risk in the project.");

  const steps = [
    ["Sweep", "Impose a moving pressure disturbance and vary its speed, direction, width and duration."],
    ["Response surface", "The output is a transfer function of the geometry, independent of any particular storm."],
    ["Inversion of the observations", "The observations cease to be the forcing and become the test, addressing whether recorded events occur under the conditions identified as resonant."],
  ];
  steps.forEach((st, i) => {
    const y = 2.55 + i * 1.28;
    badge(s, i + 1, M, y, i === 2 ? ORANGE : BLUE);
    s.addText(st[0], { x: M + 0.68, y: y - 0.02, w: 3.7, h: 0.32, fontSize: 14.5,
      bold: true, color: INK, fontFace: HEAD, isTextBox: true, margin: 0 });
    s.addText(st[1], { x: M + 0.68, y: y + 0.32, w: 6.6, h: 0.72, fontSize: 12.5,
      color: MUTED, fontFace: BODY, lineSpacing: 17, isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: 8.4, y: 2.5, w: 4.31, h: 3.4,
    fill: { color: MID }, rectRadius: 0.06 });
  s.addText("Bearing beyond the present study", { x: 8.7, y: 2.72, w: 3.75, h: 0.6,
    fontSize: 14, bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "A response surface is a property of the geometry, whereas climate change acts on the distribution of the forcing.\n", options: { breakLine: true } },
    { text: "The two separate, so the surface is computed once and any later study with synoptic projections may convolve them without repeating the hydrodynamics.\n", options: { breakLine: true } },
    { text: "No climate scenario need be run through the model.", options: { bold: true, color: WHITE } },
  ], { x: 8.7, y: 3.35, w: 3.75, h: 2.3, fontSize: 11.5, color: "CADCFC",
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  note(s, "The milgħuba floods Msida, at the head of Msida Creek inside Marsamxett, together with Marsaskala, Xemxija, Marsaxlokk and Sliema.");
  s.addNotes("A sweep of six speeds by eight directions amounts to forty-eight runs, barotropic and uncoupled, and therefore inexpensive. The sensitivity of the preceding slide is a second evaluation of the same sweep over a modified mouth, which is why it is affordable within the period.");
}

/* ---------------- 12. what to settle ---------------- */
{
  const s = p.addSlide();
  titleSlide(s, "OUTSTANDING QUESTIONS", "Six questions and their bearing on the study", null);

  const qs = [
    ["Is the sensitivity exercise on the harbour mouth one the group would consider appropriate?",
     "It is framed as a response curve over the class of basin, and it carries no assessment of the project now in consultation. The question is whether that framing is acceptable, not whether the physics holds."],
    ["Is there a sea level record inside the Grand Harbour, and at what sampling interval?",
     "A spectrum would establish whether the basins carry energy near 17 minutes. The 0.2 to 2 cph band is observed at Mellieħa, on another coast, so the present analysis can only infer the Valletta response."],
    ["Has the generation of the wave been modelled, or only its effect on a basin?",
     "The 2007 study imposes the long wave at the offshore boundary and computes the response. Modelling how the atmosphere produces that wave over the shelf is what this study proposes. Whether it is genuinely untouched is known only from a literature search."],
    ["What is the sampling interval of the PORTO sea level stations?",
     "The seiche band is 0.2 to 2 cph. At an interval coarser than one minute the model has no observational target within its own frequency range."],
    ["Is there any wave record beyond the BLUE buoy?",
     "Wave validation presently rests on a single point 3.7 km offshore. The radar reports a derived product whose own accuracy was assessed against models, so it serves as a cross-check rather than a reference."],
    ["What is the levelling datum behind the bathymetry, and how does its zero relate to the tide gauges?",
     "The files declare ellipsoidal heights while the data are orthometric. What remains to be established is the offset against the gauges used for validation."],
  ];
  qs.forEach((q, i) => {
    const col = i % 2, row = Math.floor(i / 2);
    const x = M + col * 6.08, y = 2.05 + row * 1.62;
    badge(s, i + 1, x, y, col === 0 ? BLUE : TEAL);
    s.addText(q[0], { x: x + 0.62, y: y - 0.03, w: 5.28, h: 0.52, fontSize: 12.8,
      bold: true, color: INK, fontFace: BODY, lineSpacing: 16, isTextBox: true, margin: 0 });
    s.addText(q[1], { x: x + 0.62, y: y + 0.5, w: 5.28, h: 0.98, fontSize: 11,
      color: MUTED, fontFace: BODY, lineSpacing: 14.5, isTextBox: true, margin: 0 });
  });
  s.addNotes("These items determine what the study can be, and the remainder is resolvable by execution. One question is dropped from the six because the record now answers it in part: damage inside the port is documented for the wind-wave storms of February 2019 and February 2023, and what remains open is disruption attributable to long waves specifically, held by Transport Malta and the terminals.");
}

/* ---------------- 13. immediate ---------------- */
{
  const s = p.addSlide();
  s.background = { color: MID };
  s.addShape(p.ShapeType.ellipse, { x: -1.9, y: 4.2, w: 5.2, h: 5.2,
    fill: { color: BLUE, transparency: 60 } });

  s.addText("IMMEDIATE SEQUENCE", { x: M, y: 0.7, w: 9, h: 0.3, fontSize: 12,
    bold: true, color: ORANGE, charSpacing: 2, fontFace: BODY, isTextBox: true, margin: 0 });
  s.addText("Before the mesh is built", { x: M, y: 1.05, w: 10, h: 0.7, fontSize: 30,
    bold: true, color: WHITE, fontFace: HEAD, isTextBox: true, margin: 0 });

  const tl = [
    ["Late September", "Seiche climatology from the Portomaso and PORTO archives. No model is required."],
    ["19 October", "Delft3D User Days abstract."],
    ["Early October", "Merged bathymetry over the domain, gaps intersected with the coastline."],
    ["2 to 4 November", "Delft3D User Days at Deltares, with the four configuration questions."],
    ["Late October to November", "Mesh, Riemann boundary verified by synthetic pulse, first runs."],
  ];
  // The timeline occupies the left column only, so the panel on the right has
  // its own band. An earlier arrangement ran the descriptions full width and
  // the two collided at the last two rows.
  tl.forEach((t, i) => {
    const y = 2.15 + i * 0.92;
    s.addShape(p.ShapeType.ellipse, { x: M + 0.05, y: y + 0.1, w: 0.17, h: 0.17,
      fill: { color: i === 1 ? ORANGE : "CADCFC" } });
    s.addText(t[0], { x: M + 0.45, y, w: 2.55, h: 0.33, fontSize: 13, bold: true,
      color: i === 1 ? ORANGE : WHITE, fontFace: BODY, isTextBox: true, margin: 0 });
    s.addText(t[1], { x: M + 3.1, y, w: 3.6, h: 0.72, fontSize: 12,
      color: "9FB3D1", fontFace: BODY, lineSpacing: 15, isTextBox: true, margin: 0 });
  });

  s.addShape(p.ShapeType.roundRect, { x: 7.5, y: 2.15, w: 5.21, h: 3.4,
    fill: { color: BLUE, transparency: 30 }, rectRadius: 0.06 });
  s.addText("Beyond the period", { x: 7.8, y: 2.38, w: 4.6, h: 0.3, fontSize: 14,
    bold: true, color: ORANGE, fontFace: HEAD, isTextBox: true, margin: 0 });
  s.addText([
    { text: "The Stagnone twin runs containerised on the EDITO Datalab and publishes to its object storage.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "A Valletta configuration would take the same route, so the deliverable is a running pilot rather than a set of figures.\n", options: { breakLine: true, paraSpaceAfter: 9 } },
    { text: "That is the relocatable setup the design report asks for.", options: { bold: true, color: WHITE } },
  ], { x: 7.8, y: 2.78, w: 4.6, h: 2.5, fontSize: 11.5, color: "DCE7F5",
       fontFace: BODY, lineSpacing: 15.5, isTextBox: true, margin: 0 });

  s.addText("Documents, figures and the reproducible analysis are in the project repository.",
    { x: M, y: 6.78, w: 6.4, h: 0.3, fontSize: 11, italic: true, color: "7F93B3",
      fontFace: BODY, isTextBox: true, margin: 0 });
  s.addNotes("Block B3 loses four working days to Delft and holds fifteen rather than nineteen. The EDITO deployment is conditional on the configuration proving stable in time, and it belongs to block B6 alongside the integration into the existing ocean.mt portal.");
}

p.writeFile({ fileName: OUT }).then(() => console.log("written", OUT));
